package projects.tanks.client.garage.osgi {
  import _codec.projects.tanks.client.garage.models.garage.CodecGarageModelCC;
  import _codec.projects.tanks.client.garage.models.garage.VectorCodecGarageModelCCLevel1;
  import _codec.projects.tanks.client.garage.models.garage.passtoshop.CodecPassToShopCC;
  import _codec.projects.tanks.client.garage.models.garage.passtoshop.VectorCodecPassToShopCCLevel1;
  import _codec.projects.tanks.client.garage.models.garage.temperature.CodecTemperatureCC;
  import _codec.projects.tanks.client.garage.models.garage.temperature.VectorCodecTemperatureCCLevel1;
  import _codec.projects.tanks.client.garage.models.garagepreview.CodecGaragePreviewModelCC;
  import _codec.projects.tanks.client.garage.models.garagepreview.VectorCodecGaragePreviewModelCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.buyable.CodecBuyableCC;
  import _codec.projects.tanks.client.garage.models.item.buyable.VectorCodecBuyableCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.category.CodecItemCategoryCC;
  import _codec.projects.tanks.client.garage.models.item.category.VectorCodecItemCategoryCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.container.CodecContainerGivenItem;
  import _codec.projects.tanks.client.garage.models.item.container.CodecContainerItemCategory;
  import _codec.projects.tanks.client.garage.models.item.container.VectorCodecContainerGivenItemLevel1;
  import _codec.projects.tanks.client.garage.models.item.container.VectorCodecContainerItemCategoryLevel1;
  import _codec.projects.tanks.client.garage.models.item.container.resources.CodecContainerResourceCC;
  import _codec.projects.tanks.client.garage.models.item.container.resources.VectorCodecContainerResourceCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.countable.CodecCountableItemCC;
  import _codec.projects.tanks.client.garage.models.item.countable.VectorCodecCountableItemCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.delaymount.CodecDelayMountCategoryCC;
  import _codec.projects.tanks.client.garage.models.item.delaymount.VectorCodecDelayMountCategoryCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.device.CodecItemDevicesCC;
  import _codec.projects.tanks.client.garage.models.item.device.VectorCodecItemDevicesCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.discount.CodecDiscountCC;
  import _codec.projects.tanks.client.garage.models.item.discount.VectorCodecDiscountCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.discount.proabonement.CodecProAbonementRankDiscountCC;
  import _codec.projects.tanks.client.garage.models.item.discount.proabonement.VectorCodecProAbonementRankDiscountCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.drone.CodecHasBatteriesNotifyCC;
  import _codec.projects.tanks.client.garage.models.item.drone.VectorCodecHasBatteriesNotifyCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.droppablegold.CodecDroppableGoldItemCC;
  import _codec.projects.tanks.client.garage.models.item.droppablegold.VectorCodecDroppableGoldItemCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.grouped.CodecGroupedCC;
  import _codec.projects.tanks.client.garage.models.item.grouped.VectorCodecGroupedCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.item.CodecItemModelCC;
  import _codec.projects.tanks.client.garage.models.item.item.VectorCodecItemModelCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.item3d.CodecItem3DCC;
  import _codec.projects.tanks.client.garage.models.item.item3d.VectorCodecItem3DCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.itemforpartners.CodecItemEnabledForPartnerCC;
  import _codec.projects.tanks.client.garage.models.item.itemforpartners.VectorCodecItemEnabledForPartnerCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.itempersonaldiscount.CodecDiscountData;
  import _codec.projects.tanks.client.garage.models.item.itempersonaldiscount.CodecItemPersonalDiscountCC;
  import _codec.projects.tanks.client.garage.models.item.itempersonaldiscount.VectorCodecDiscountDataLevel1;
  import _codec.projects.tanks.client.garage.models.item.itempersonaldiscount.VectorCodecItemPersonalDiscountCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.kit.CodecGarageKitCC;
  import _codec.projects.tanks.client.garage.models.item.kit.CodecKitItem;
  import _codec.projects.tanks.client.garage.models.item.kit.VectorCodecGarageKitCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.kit.VectorCodecKitItemLevel1;
  import _codec.projects.tanks.client.garage.models.item.mobilelootbox.deliverylootbox.CodecMobileLootBoxDeliveryCC;
  import _codec.projects.tanks.client.garage.models.item.mobilelootbox.deliverylootbox.VectorCodecMobileLootBoxDeliveryCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.mobilelootbox.lootbox.CodecMobileLoot;
  import _codec.projects.tanks.client.garage.models.item.mobilelootbox.lootbox.VectorCodecMobileLootLevel1;
  import _codec.projects.tanks.client.garage.models.item.modification.CodecModificationCC;
  import _codec.projects.tanks.client.garage.models.item.modification.VectorCodecModificationCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.object3ds.CodecObject3DSCC;
  import _codec.projects.tanks.client.garage.models.item.object3ds.VectorCodecObject3DSCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.premium.CodecPremiumItemCC;
  import _codec.projects.tanks.client.garage.models.item.premium.VectorCodecPremiumItemCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.present.CodecPresentItemCC;
  import _codec.projects.tanks.client.garage.models.item.present.VectorCodecPresentItemCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.properties.CodecItemGaragePropertyData;
  import _codec.projects.tanks.client.garage.models.item.properties.CodecItemPropertiesCC;
  import _codec.projects.tanks.client.garage.models.item.properties.CodecItemProperty;
  import _codec.projects.tanks.client.garage.models.item.properties.VectorCodecItemGaragePropertyDataLevel1;
  import _codec.projects.tanks.client.garage.models.item.properties.VectorCodecItemPropertiesCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.properties.VectorCodecItemPropertyLevel1;
  import _codec.projects.tanks.client.garage.models.item.rarity.CodecItemRarityCC;
  import _codec.projects.tanks.client.garage.models.item.rarity.CodecRarity;
  import _codec.projects.tanks.client.garage.models.item.rarity.VectorCodecItemRarityCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.rarity.VectorCodecRarityLevel1;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.CodecRelativeProperties;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.CodecRelativePropertiesCC;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.CodecRelativeProperty;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.VectorCodecRelativePropertiesCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.VectorCodecRelativePropertiesLevel1;
  import _codec.projects.tanks.client.garage.models.item.relativeproperties.VectorCodecRelativePropertyLevel1;
  import _codec.projects.tanks.client.garage.models.item.resistance.CodecMountedResistancesCC;
  import _codec.projects.tanks.client.garage.models.item.resistance.VectorCodecMountedResistancesCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.temporary.CodecTemporaryItemCC;
  import _codec.projects.tanks.client.garage.models.item.temporary.VectorCodecTemporaryItemCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.CodecUpgradeParamsCC;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.VectorCodecUpgradeParamsCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.CodecGaragePropertyParams;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.CodecPropertyData;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.CodecUpgradeParamsData;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.VectorCodecGaragePropertyParamsLevel1;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.VectorCodecPropertyDataLevel1;
  import _codec.projects.tanks.client.garage.models.item.upgradeable.types.VectorCodecUpgradeParamsDataLevel1;
  import _codec.projects.tanks.client.garage.models.item.videoads.CodecVideoAdsItemUpgradeCC;
  import _codec.projects.tanks.client.garage.models.item.videoads.VectorCodecVideoAdsItemUpgradeCCLevel1;
  import _codec.projects.tanks.client.garage.models.item.view.CodecItemViewCategoryCC;
  import _codec.projects.tanks.client.garage.models.item.view.VectorCodecItemViewCategoryCCLevel1;
  import _codec.projects.tanks.client.garage.models.shopabonement.CodecShopAbonementCC;
  import _codec.projects.tanks.client.garage.models.shopabonement.VectorCodecShopAbonementCCLevel1;
  import _codec.projects.tanks.client.garage.models.user.present.CodecPresentItem;
  import _codec.projects.tanks.client.garage.models.user.present.CodecPresentsCC;
  import _codec.projects.tanks.client.garage.models.user.present.VectorCodecPresentItemLevel1;
  import _codec.projects.tanks.client.garage.models.user.present.VectorCodecPresentsCCLevel1;
  import _codec.projects.tanks.client.garage.skins.CodecAvailableSkinsCC;
  import _codec.projects.tanks.client.garage.skins.CodecMountedSkinCC;
  import _codec.projects.tanks.client.garage.skins.VectorCodecAvailableSkinsCCLevel1;
  import _codec.projects.tanks.client.garage.skins.VectorCodecMountedSkinCCLevel1;
  import _codec.projects.tanks.client.garage.skins.shot.CodecAvailableShotSkinsCC;
  import _codec.projects.tanks.client.garage.skins.shot.VectorCodecAvailableShotSkinsCCLevel1;
  import alternativa.osgi.OSGi;
  import alternativa.osgi.bundle.IBundleActivator;
  import alternativa.protocol.ICodec;
  import alternativa.protocol.IProtocol;
  import alternativa.protocol.codec.OptionalCodecDecorator;
  import alternativa.protocol.info.CollectionCodecInfo;
  import alternativa.protocol.info.EnumCodecInfo;
  import alternativa.protocol.info.TypeCodecInfo;
  import alternativa.types.Long;
  import platform.client.fp10.core.registry.ModelRegistry;
  import projects.tanks.client.garage.models.garage.GarageModelCC;
  import projects.tanks.client.garage.models.garage.passtoshop.PassToShopCC;
  import projects.tanks.client.garage.models.garage.temperature.TemperatureCC;
  import projects.tanks.client.garage.models.garagepreview.GaragePreviewModelCC;
  import projects.tanks.client.garage.models.item.buyable.BuyableCC;
  import projects.tanks.client.garage.models.item.category.ItemCategoryCC;
  import projects.tanks.client.garage.models.item.container.ContainerGivenItem;
  import projects.tanks.client.garage.models.item.container.ContainerItemCategory;
  import projects.tanks.client.garage.models.item.container.resources.ContainerResourceCC;
  import projects.tanks.client.garage.models.item.countable.CountableItemCC;
  import projects.tanks.client.garage.models.item.delaymount.DelayMountCategoryCC;
  import projects.tanks.client.garage.models.item.device.ItemDevicesCC;
  import projects.tanks.client.garage.models.item.discount.DiscountCC;
  import projects.tanks.client.garage.models.item.discount.proabonement.ProAbonementRankDiscountCC;
  import projects.tanks.client.garage.models.item.drone.HasBatteriesNotifyCC;
  import projects.tanks.client.garage.models.item.droppablegold.DroppableGoldItemCC;
  import projects.tanks.client.garage.models.item.grouped.GroupedCC;
  import projects.tanks.client.garage.models.item.item.ItemModelCC;
  import projects.tanks.client.garage.models.item.item3d.Item3DCC;
  import projects.tanks.client.garage.models.item.itemforpartners.ItemEnabledForPartnerCC;
  import projects.tanks.client.garage.models.item.itempersonaldiscount.DiscountData;
  import projects.tanks.client.garage.models.item.itempersonaldiscount.ItemPersonalDiscountCC;
  import projects.tanks.client.garage.models.item.kit.GarageKitCC;
  import projects.tanks.client.garage.models.item.kit.KitItem;
  import projects.tanks.client.garage.models.item.mobilelootbox.deliverylootbox.MobileLootBoxDeliveryCC;
  import projects.tanks.client.garage.models.item.mobilelootbox.lootbox.MobileLoot;
  import projects.tanks.client.garage.models.item.modification.ModificationCC;
  import projects.tanks.client.garage.models.item.object3ds.Object3DSCC;
  import projects.tanks.client.garage.models.item.premium.PremiumItemCC;
  import projects.tanks.client.garage.models.item.present.PresentItemCC;
  import projects.tanks.client.garage.models.item.properties.ItemGaragePropertyData;
  import projects.tanks.client.garage.models.item.properties.ItemPropertiesCC;
  import projects.tanks.client.garage.models.item.properties.ItemProperty;
  import projects.tanks.client.garage.models.item.rarity.ItemRarityCC;
  import projects.tanks.client.garage.models.item.rarity.Rarity;
  import projects.tanks.client.garage.models.item.relativeproperties.RelativeProperties;
  import projects.tanks.client.garage.models.item.relativeproperties.RelativePropertiesCC;
  import projects.tanks.client.garage.models.item.relativeproperties.RelativeProperty;
  import projects.tanks.client.garage.models.item.resistance.MountedResistancesCC;
  import projects.tanks.client.garage.models.item.temporary.TemporaryItemCC;
  import projects.tanks.client.garage.models.item.upgradeable.UpgradeParamsCC;
  import projects.tanks.client.garage.models.item.upgradeable.types.GaragePropertyParams;
  import projects.tanks.client.garage.models.item.upgradeable.types.PropertyData;
  import projects.tanks.client.garage.models.item.upgradeable.types.UpgradeParamsData;
  import projects.tanks.client.garage.models.item.videoads.VideoAdsItemUpgradeCC;
  import projects.tanks.client.garage.models.item.view.ItemViewCategoryCC;
  import projects.tanks.client.garage.models.shopabonement.ShopAbonementCC;
  import projects.tanks.client.garage.models.user.present.PresentItem;
  import projects.tanks.client.garage.models.user.present.PresentsCC;
  import projects.tanks.client.garage.skins.AvailableSkinsCC;
  import projects.tanks.client.garage.skins.MountedSkinCC;
  import projects.tanks.client.garage.skins.shot.AvailableShotSkinsCC;

  public class Activator implements IBundleActivator {
    public static var osgi:OSGi;

    public function Activator() {
      super();
    }

    public function start(param1:OSGi) : void {
      var local4:ICodec = null;
      osgi = param1;
      var local2:ModelRegistry = ModelRegistry(OSGi.getInstance().getService(ModelRegistry));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(930502521,-307520123));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(1219192892,689165557));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(859726007,514386313));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(933245382,1068161023));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(1177280707,-1253059324));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(1672979457,540290587));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(450776038,1263898393));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(939753622,116528378));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(952716796,14349239));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(2006024142,-2135822943));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(1235090973,1845524944));
      local2.register(Long.getLong(1718746868,-1910730614),Long.getLong(1589955723,815412220));
      local2.register(Long.getLong(888433053,2115284408),Long.getLong(759000870,-1549014702));
      local2.register(Long.getLong(293210276,-627719811),Long.getLong(2126423224,-768730341));
      local2.register(Long.getLong(868501559,1837500388),Long.getLong(1619306003,844016486));
      local2.register(Long.getLong(104346758,-1948098183),Long.getLong(1773038483,1761949850));
      local2.register(Long.getLong(1980083488,639502934),Long.getLong(910382979,820768829));
      local2.register(Long.getLong(1980083488,639502934),Long.getLong(447542744,65837337));
      local2.register(Long.getLong(895763411,-290717027),Long.getLong(414752496,-1868458890));
      local2.register(Long.getLong(895763411,-290717027),Long.getLong(1978161324,62150420));
      local2.register(Long.getLong(563557196,-1799629517),Long.getLong(1519071544,-862454895));
      local2.register(Long.getLong(793986940,265050196),Long.getLong(812687689,208178107));
      local2.register(Long.getLong(793986940,265050196),Long.getLong(857495400,624501804));
      local2.register(Long.getLong(793986940,265050196),Long.getLong(1398628694,-1349788069));
      local2.register(Long.getLong(1632109435,-443674078),Long.getLong(1354999069,-1103449185));
      local2.register(Long.getLong(841189855,-1268110049),Long.getLong(1282635693,192675762));
      local2.register(Long.getLong(841189855,-1268110049),Long.getLong(2064863564,657165826));
      var local3:IProtocol = IProtocol(osgi.getService(IProtocol));
      local4 = new CodecGarageModelCC();
      local3.registerCodec(new TypeCodecInfo(GarageModelCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(GarageModelCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPassToShopCC();
      local3.registerCodec(new TypeCodecInfo(PassToShopCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PassToShopCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecTemperatureCC();
      local3.registerCodec(new TypeCodecInfo(TemperatureCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(TemperatureCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGaragePreviewModelCC();
      local3.registerCodec(new TypeCodecInfo(GaragePreviewModelCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(GaragePreviewModelCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBuyableCC();
      local3.registerCodec(new TypeCodecInfo(BuyableCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(BuyableCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemCategoryCC();
      local3.registerCodec(new TypeCodecInfo(ItemCategoryCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemCategoryCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecContainerGivenItem();
      local3.registerCodec(new TypeCodecInfo(ContainerGivenItem,false),local4);
      local3.registerCodec(new TypeCodecInfo(ContainerGivenItem,true),new OptionalCodecDecorator(local4));
      local4 = new CodecContainerItemCategory();
      local3.registerCodec(new EnumCodecInfo(ContainerItemCategory,false),local4);
      local3.registerCodec(new EnumCodecInfo(ContainerItemCategory,true),new OptionalCodecDecorator(local4));
      local4 = new CodecContainerResourceCC();
      local3.registerCodec(new TypeCodecInfo(ContainerResourceCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ContainerResourceCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecCountableItemCC();
      local3.registerCodec(new TypeCodecInfo(CountableItemCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(CountableItemCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecDelayMountCategoryCC();
      local3.registerCodec(new TypeCodecInfo(DelayMountCategoryCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(DelayMountCategoryCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemDevicesCC();
      local3.registerCodec(new TypeCodecInfo(ItemDevicesCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemDevicesCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecDiscountCC();
      local3.registerCodec(new TypeCodecInfo(DiscountCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(DiscountCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecProAbonementRankDiscountCC();
      local3.registerCodec(new TypeCodecInfo(ProAbonementRankDiscountCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ProAbonementRankDiscountCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecHasBatteriesNotifyCC();
      local3.registerCodec(new TypeCodecInfo(HasBatteriesNotifyCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(HasBatteriesNotifyCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecDroppableGoldItemCC();
      local3.registerCodec(new TypeCodecInfo(DroppableGoldItemCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(DroppableGoldItemCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGroupedCC();
      local3.registerCodec(new TypeCodecInfo(GroupedCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(GroupedCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemModelCC();
      local3.registerCodec(new TypeCodecInfo(ItemModelCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemModelCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItem3DCC();
      local3.registerCodec(new TypeCodecInfo(Item3DCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(Item3DCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemEnabledForPartnerCC();
      local3.registerCodec(new TypeCodecInfo(ItemEnabledForPartnerCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemEnabledForPartnerCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecDiscountData();
      local3.registerCodec(new TypeCodecInfo(DiscountData,false),local4);
      local3.registerCodec(new TypeCodecInfo(DiscountData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemPersonalDiscountCC();
      local3.registerCodec(new TypeCodecInfo(ItemPersonalDiscountCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemPersonalDiscountCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGarageKitCC();
      local3.registerCodec(new TypeCodecInfo(GarageKitCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(GarageKitCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecKitItem();
      local3.registerCodec(new TypeCodecInfo(KitItem,false),local4);
      local3.registerCodec(new TypeCodecInfo(KitItem,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMobileLootBoxDeliveryCC();
      local3.registerCodec(new TypeCodecInfo(MobileLootBoxDeliveryCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MobileLootBoxDeliveryCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMobileLoot();
      local3.registerCodec(new TypeCodecInfo(MobileLoot,false),local4);
      local3.registerCodec(new TypeCodecInfo(MobileLoot,true),new OptionalCodecDecorator(local4));
      local4 = new CodecModificationCC();
      local3.registerCodec(new TypeCodecInfo(ModificationCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ModificationCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecObject3DSCC();
      local3.registerCodec(new TypeCodecInfo(Object3DSCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(Object3DSCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPremiumItemCC();
      local3.registerCodec(new TypeCodecInfo(PremiumItemCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PremiumItemCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPresentItemCC();
      local3.registerCodec(new TypeCodecInfo(PresentItemCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PresentItemCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemGaragePropertyData();
      local3.registerCodec(new TypeCodecInfo(ItemGaragePropertyData,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemGaragePropertyData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemPropertiesCC();
      local3.registerCodec(new TypeCodecInfo(ItemPropertiesCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemPropertiesCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemProperty();
      local3.registerCodec(new EnumCodecInfo(ItemProperty,false),local4);
      local3.registerCodec(new EnumCodecInfo(ItemProperty,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemRarityCC();
      local3.registerCodec(new TypeCodecInfo(ItemRarityCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemRarityCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRarity();
      local3.registerCodec(new EnumCodecInfo(Rarity,false),local4);
      local3.registerCodec(new EnumCodecInfo(Rarity,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRelativeProperties();
      local3.registerCodec(new EnumCodecInfo(RelativeProperties,false),local4);
      local3.registerCodec(new EnumCodecInfo(RelativeProperties,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRelativePropertiesCC();
      local3.registerCodec(new TypeCodecInfo(RelativePropertiesCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(RelativePropertiesCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRelativeProperty();
      local3.registerCodec(new TypeCodecInfo(RelativeProperty,false),local4);
      local3.registerCodec(new TypeCodecInfo(RelativeProperty,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMountedResistancesCC();
      local3.registerCodec(new TypeCodecInfo(MountedResistancesCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MountedResistancesCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecTemporaryItemCC();
      local3.registerCodec(new TypeCodecInfo(TemporaryItemCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(TemporaryItemCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUpgradeParamsCC();
      local3.registerCodec(new TypeCodecInfo(UpgradeParamsCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(UpgradeParamsCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGaragePropertyParams();
      local3.registerCodec(new TypeCodecInfo(GaragePropertyParams,false),local4);
      local3.registerCodec(new TypeCodecInfo(GaragePropertyParams,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPropertyData();
      local3.registerCodec(new TypeCodecInfo(PropertyData,false),local4);
      local3.registerCodec(new TypeCodecInfo(PropertyData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUpgradeParamsData();
      local3.registerCodec(new TypeCodecInfo(UpgradeParamsData,false),local4);
      local3.registerCodec(new TypeCodecInfo(UpgradeParamsData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecVideoAdsItemUpgradeCC();
      local3.registerCodec(new TypeCodecInfo(VideoAdsItemUpgradeCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(VideoAdsItemUpgradeCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemViewCategoryCC();
      local3.registerCodec(new TypeCodecInfo(ItemViewCategoryCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ItemViewCategoryCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecShopAbonementCC();
      local3.registerCodec(new TypeCodecInfo(ShopAbonementCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ShopAbonementCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPresentItem();
      local3.registerCodec(new TypeCodecInfo(PresentItem,false),local4);
      local3.registerCodec(new TypeCodecInfo(PresentItem,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPresentsCC();
      local3.registerCodec(new TypeCodecInfo(PresentsCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PresentsCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecAvailableSkinsCC();
      local3.registerCodec(new TypeCodecInfo(AvailableSkinsCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(AvailableSkinsCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMountedSkinCC();
      local3.registerCodec(new TypeCodecInfo(MountedSkinCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MountedSkinCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecAvailableShotSkinsCC();
      local3.registerCodec(new TypeCodecInfo(AvailableShotSkinsCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(AvailableShotSkinsCC,true),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageModelCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageModelCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageModelCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageModelCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageModelCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageModelCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPassToShopCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PassToShopCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PassToShopCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPassToShopCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PassToShopCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PassToShopCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTemperatureCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemperatureCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemperatureCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTemperatureCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemperatureCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemperatureCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGaragePreviewModelCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePreviewModelCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePreviewModelCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGaragePreviewModelCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePreviewModelCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePreviewModelCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBuyableCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BuyableCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BuyableCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBuyableCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BuyableCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BuyableCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemCategoryCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemCategoryCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemCategoryCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemCategoryCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemCategoryCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemCategoryCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerGivenItemLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerGivenItem,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerGivenItem,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerGivenItemLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerGivenItem,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerGivenItem,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerItemCategoryLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ContainerItemCategory,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ContainerItemCategory,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerItemCategoryLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ContainerItemCategory,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ContainerItemCategory,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerResourceCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerResourceCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerResourceCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecContainerResourceCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerResourceCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ContainerResourceCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCountableItemCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CountableItemCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CountableItemCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCountableItemCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CountableItemCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CountableItemCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDelayMountCategoryCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DelayMountCategoryCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DelayMountCategoryCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDelayMountCategoryCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DelayMountCategoryCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DelayMountCategoryCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemDevicesCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemDevicesCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemDevicesCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemDevicesCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemDevicesCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemDevicesCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDiscountCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDiscountCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecProAbonementRankDiscountCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementRankDiscountCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementRankDiscountCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecProAbonementRankDiscountCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementRankDiscountCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementRankDiscountCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecHasBatteriesNotifyCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(HasBatteriesNotifyCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(HasBatteriesNotifyCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecHasBatteriesNotifyCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(HasBatteriesNotifyCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(HasBatteriesNotifyCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDroppableGoldItemCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DroppableGoldItemCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DroppableGoldItemCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDroppableGoldItemCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DroppableGoldItemCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DroppableGoldItemCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGroupedCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GroupedCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GroupedCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGroupedCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GroupedCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GroupedCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemModelCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemModelCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemModelCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemModelCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemModelCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemModelCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItem3DCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Item3DCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Item3DCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItem3DCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Item3DCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Item3DCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemEnabledForPartnerCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemEnabledForPartnerCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemEnabledForPartnerCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemEnabledForPartnerCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemEnabledForPartnerCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemEnabledForPartnerCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDiscountDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDiscountDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DiscountData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPersonalDiscountCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPersonalDiscountCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPersonalDiscountCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPersonalDiscountCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPersonalDiscountCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPersonalDiscountCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageKitCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageKitCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageKitCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageKitCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageKitCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GarageKitCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecKitItemLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(KitItem,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(KitItem,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecKitItemLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(KitItem,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(KitItem,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMobileLootBoxDeliveryCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLootBoxDeliveryCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLootBoxDeliveryCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMobileLootBoxDeliveryCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLootBoxDeliveryCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLootBoxDeliveryCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMobileLootLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLoot,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLoot,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMobileLootLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLoot,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MobileLoot,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecModificationCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ModificationCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ModificationCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecModificationCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ModificationCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ModificationCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecObject3DSCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Object3DSCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Object3DSCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecObject3DSCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Object3DSCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Object3DSCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPremiumItemCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumItemCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumItemCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPremiumItemCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumItemCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumItemCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentItemCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItemCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItemCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentItemCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItemCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItemCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemGaragePropertyDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemGaragePropertyData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemGaragePropertyData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemGaragePropertyDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemGaragePropertyData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemGaragePropertyData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPropertiesCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPropertiesCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPropertiesCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPropertiesCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPropertiesCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemPropertiesCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPropertyLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemProperty,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemProperty,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemPropertyLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemProperty,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemProperty,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemRarityCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemRarityCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemRarityCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemRarityCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemRarityCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemRarityCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRarityLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(Rarity,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(Rarity,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRarityLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(Rarity,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(Rarity,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertiesCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativePropertiesCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativePropertiesCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertiesCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativePropertiesCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativePropertiesCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertiesLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(RelativeProperties,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(RelativeProperties,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertiesLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(RelativeProperties,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(RelativeProperties,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertyLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativeProperty,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativeProperty,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRelativePropertyLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativeProperty,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RelativeProperty,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountedResistancesCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedResistancesCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedResistancesCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountedResistancesCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedResistancesCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedResistancesCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTemporaryItemCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemporaryItemCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemporaryItemCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTemporaryItemCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemporaryItemCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TemporaryItemCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUpgradeParamsCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUpgradeParamsCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGaragePropertyParamsLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePropertyParams,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePropertyParams,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGaragePropertyParamsLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePropertyParams,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(GaragePropertyParams,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPropertyDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PropertyData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PropertyData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPropertyDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PropertyData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PropertyData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUpgradeParamsDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUpgradeParamsDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UpgradeParamsData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecVideoAdsItemUpgradeCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(VideoAdsItemUpgradeCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(VideoAdsItemUpgradeCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecVideoAdsItemUpgradeCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(VideoAdsItemUpgradeCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(VideoAdsItemUpgradeCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemViewCategoryCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemViewCategoryCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemViewCategoryCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemViewCategoryCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemViewCategoryCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ItemViewCategoryCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopAbonementCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ShopAbonementCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ShopAbonementCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopAbonementCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ShopAbonementCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ShopAbonementCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentItemLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItem,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItem,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentItemLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItem,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentItem,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentsCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentsCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentsCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPresentsCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentsCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PresentsCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAvailableSkinsCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableSkinsCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableSkinsCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAvailableSkinsCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableSkinsCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableSkinsCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountedSkinCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedSkinCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedSkinCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountedSkinCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedSkinCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountedSkinCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAvailableShotSkinsCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableShotSkinsCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableShotSkinsCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAvailableShotSkinsCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableShotSkinsCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AvailableShotSkinsCC,true),true,1),new OptionalCodecDecorator(local4));
    }

    public function stop(param1:OSGi) : void {
    }
  }
}
