package projects.tanks.client.battleselect.osgi {
  import _codec.projects.tanks.client.battleselect.model.battle.CodecBattleInfoCC;
  import _codec.projects.tanks.client.battleselect.model.battle.VectorCodecBattleInfoCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.battle.dm.CodecBattleDMInfoCC;
  import _codec.projects.tanks.client.battleselect.model.battle.dm.VectorCodecBattleDMInfoCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.battle.entrance.user.CodecBattleInfoUser;
  import _codec.projects.tanks.client.battleselect.model.battle.entrance.user.VectorCodecBattleInfoUserLevel1;
  import _codec.projects.tanks.client.battleselect.model.battle.param.CodecBattleParamInfoCC;
  import _codec.projects.tanks.client.battleselect.model.battle.param.VectorCodecBattleParamInfoCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.battle.team.CodecTeamBattleInfoCC;
  import _codec.projects.tanks.client.battleselect.model.battle.team.VectorCodecTeamBattleInfoCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.battleselect.create.CodecBattleCreateCC;
  import _codec.projects.tanks.client.battleselect.model.battleselect.create.VectorCodecBattleCreateCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.map.CodecMapInfoCC;
  import _codec.projects.tanks.client.battleselect.model.map.VectorCodecMapInfoCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.invitewindow.CodecMatchMakingUserInfo;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.invitewindow.VectorCodecMatchMakingUserInfoLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.CodecMatchmakingGroupCC;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.CodecMatchmakingUserData;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.CodecMountItemsUserData;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.VectorCodecMatchmakingGroupCCLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.VectorCodecMatchmakingUserDataLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.group.notify.VectorCodecMountItemsUserDataLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.modes.CodecMatchmakingModeRank;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.modes.VectorCodecMatchmakingModeRankLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.queue.CodecMatchmakingMode;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.queue.VectorCodecMatchmakingModeLevel1;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.view.CodecMatchmakingLayoutCC;
  import _codec.projects.tanks.client.battleselect.model.matchmaking.view.VectorCodecMatchmakingLayoutCCLevel1;
  import alternativa.osgi.OSGi;
  import alternativa.osgi.bundle.IBundleActivator;
  import alternativa.protocol.ICodec;
  import alternativa.protocol.IProtocol;
  import alternativa.protocol.codec.OptionalCodecDecorator;
  import alternativa.protocol.info.CollectionCodecInfo;
  import alternativa.protocol.info.EnumCodecInfo;
  import alternativa.protocol.info.TypeCodecInfo;
  import alternativa.types.Long;
  import platform.client.fp10.core.registry.ModelRegistry;
  import projects.tanks.client.battleselect.model.battle.BattleInfoCC;
  import projects.tanks.client.battleselect.model.battle.dm.BattleDMInfoCC;
  import projects.tanks.client.battleselect.model.battle.entrance.user.BattleInfoUser;
  import projects.tanks.client.battleselect.model.battle.param.BattleParamInfoCC;
  import projects.tanks.client.battleselect.model.battle.team.TeamBattleInfoCC;
  import projects.tanks.client.battleselect.model.battleselect.create.BattleCreateCC;
  import projects.tanks.client.battleselect.model.map.MapInfoCC;
  import projects.tanks.client.battleselect.model.matchmaking.group.invitewindow.MatchMakingUserInfo;
  import projects.tanks.client.battleselect.model.matchmaking.group.notify.MatchmakingGroupCC;
  import projects.tanks.client.battleselect.model.matchmaking.group.notify.MatchmakingUserData;
  import projects.tanks.client.battleselect.model.matchmaking.group.notify.MountItemsUserData;
  import projects.tanks.client.battleselect.model.matchmaking.modes.MatchmakingModeRank;
  import projects.tanks.client.battleselect.model.matchmaking.queue.MatchmakingMode;
  import projects.tanks.client.battleselect.model.matchmaking.view.MatchmakingLayoutCC;

  public class Activator implements IBundleActivator {
    public static var osgi:OSGi;

    public function Activator() {
      super();
    }

    public function start(param1:OSGi) : void {
      var local4:ICodec = null;
      osgi = param1;
      var local2:ModelRegistry = ModelRegistry(OSGi.getInstance().getService(ModelRegistry));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(1723702817,-1559950205));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(2079393446,1872275759));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(1595490780,1527833154));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(1955622129,800057322));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(1794766139,-788021385));
      local2.register(Long.getLong(678248814,-1039722970),Long.getLong(571437576,1704127087));
      local2.register(Long.getLong(231608534,1754662850),Long.getLong(1280686572,-165446809));
      local2.register(Long.getLong(231608534,1754662850),Long.getLong(739099814,-1836001986));
      local2.register(Long.getLong(231608534,1754662850),Long.getLong(1545032099,1699072587));
      local2.register(Long.getLong(124040719,-2122162804),Long.getLong(1427344653,-225635033));
      local2.register(Long.getLong(124040719,-2122162804),Long.getLong(1971172597,1526425495));
      local2.register(Long.getLong(124040719,-2122162804),Long.getLong(1465029547,1591202968));
      local2.register(Long.getLong(1548819686,-690668258),Long.getLong(1082637975,-979180615));
      local2.register(Long.getLong(1548819686,-690668258),Long.getLong(1958615472,-14223454));
      local2.register(Long.getLong(1548819686,-690668258),Long.getLong(1033012780,-1733683120));
      local2.register(Long.getLong(1548819686,-690668258),Long.getLong(344688414,904593895));
      local2.register(Long.getLong(1548819686,-690668258),Long.getLong(344688125,389346965));
      local2.register(Long.getLong(600945976,725191480),Long.getLong(1673040790,-1477360154));
      local2.register(Long.getLong(600945976,725191480),Long.getLong(1230896613,-954387929));
      local2.register(Long.getLong(2006601986,1009878384),Long.getLong(197885668,-2032708814));
      local2.register(Long.getLong(2006601986,1009878384),Long.getLong(1756028652,-1657837994));
      local2.register(Long.getLong(2006601986,1009878384),Long.getLong(872763403,679070993));
      local2.register(Long.getLong(2006601986,1009878384),Long.getLong(1102481331,-1022378385));
      local2.register(Long.getLong(2006601986,1009878384),Long.getLong(1263225061,56978839));
      local2.register(Long.getLong(443203981,347316300),Long.getLong(64042174,-63295164));
      local2.register(Long.getLong(443203981,347316300),Long.getLong(1229034573,1475867490));
      local2.register(Long.getLong(24345264,-1141305498),Long.getLong(457644934,1356384143));
      local2.register(Long.getLong(24345264,-1141305498),Long.getLong(1473935785,1650079766));
      local2.register(Long.getLong(24345264,-1141305498),Long.getLong(796961862,-1942684603));
      local2.register(Long.getLong(24345264,-1141305498),Long.getLong(907288320,709901878));
      local2.register(Long.getLong(24345264,-1141305498),Long.getLong(1710113617,1839810627));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(1122035593,599020768));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(490134730,1080398833));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(473112343,1371826939));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(374808837,1597389024));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(1122035483,-939007991));
      local2.register(Long.getLong(1554280211,1562501796),Long.getLong(239302436,-1286419946));
      local2.register(Long.getLong(1668041838,-577067222),Long.getLong(1292268413,1208036615));
      local2.register(Long.getLong(1668041838,-577067222),Long.getLong(930952614,-2058633481));
      local2.register(Long.getLong(1668041838,-577067222),Long.getLong(1706073111,946529251));
      local2.register(Long.getLong(2143871783,-1643323062),Long.getLong(57273342,86368579));
      local2.register(Long.getLong(1381232317,979335603),Long.getLong(684570251,-10047503));
      local2.register(Long.getLong(1381232317,979335603),Long.getLong(741085905,-1689593046));
      var local3:IProtocol = IProtocol(osgi.getService(IProtocol));
      local4 = new CodecBattleInfoCC();
      local3.registerCodec(new TypeCodecInfo(BattleInfoCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleInfoCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleDMInfoCC();
      local3.registerCodec(new TypeCodecInfo(BattleDMInfoCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleDMInfoCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleInfoUser();
      local3.registerCodec(new TypeCodecInfo(BattleInfoUser,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleInfoUser,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleParamInfoCC();
      local3.registerCodec(new TypeCodecInfo(BattleParamInfoCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleParamInfoCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecTeamBattleInfoCC();
      local3.registerCodec(new TypeCodecInfo(TeamBattleInfoCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(TeamBattleInfoCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleCreateCC();
      local3.registerCodec(new TypeCodecInfo(BattleCreateCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleCreateCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMapInfoCC();
      local3.registerCodec(new TypeCodecInfo(MapInfoCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MapInfoCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchMakingUserInfo();
      local3.registerCodec(new TypeCodecInfo(MatchMakingUserInfo,false),local4);
      local3.registerCodec(new TypeCodecInfo(MatchMakingUserInfo,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchmakingGroupCC();
      local3.registerCodec(new TypeCodecInfo(MatchmakingGroupCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MatchmakingGroupCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchmakingUserData();
      local3.registerCodec(new TypeCodecInfo(MatchmakingUserData,false),local4);
      local3.registerCodec(new TypeCodecInfo(MatchmakingUserData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMountItemsUserData();
      local3.registerCodec(new TypeCodecInfo(MountItemsUserData,false),local4);
      local3.registerCodec(new TypeCodecInfo(MountItemsUserData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchmakingModeRank();
      local3.registerCodec(new TypeCodecInfo(MatchmakingModeRank,false),local4);
      local3.registerCodec(new TypeCodecInfo(MatchmakingModeRank,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchmakingMode();
      local3.registerCodec(new EnumCodecInfo(MatchmakingMode,false),local4);
      local3.registerCodec(new EnumCodecInfo(MatchmakingMode,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMatchmakingLayoutCC();
      local3.registerCodec(new TypeCodecInfo(MatchmakingLayoutCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(MatchmakingLayoutCC,true),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleDMInfoCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleDMInfoCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleDMInfoCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleDMInfoCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleDMInfoCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleDMInfoCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoUserLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoUser,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoUser,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoUserLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoUser,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoUser,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleParamInfoCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleParamInfoCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleParamInfoCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleParamInfoCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleParamInfoCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleParamInfoCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTeamBattleInfoCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TeamBattleInfoCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TeamBattleInfoCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecTeamBattleInfoCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TeamBattleInfoCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(TeamBattleInfoCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleCreateCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleCreateCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMapInfoCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MapInfoCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MapInfoCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMapInfoCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MapInfoCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MapInfoCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchMakingUserInfoLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchMakingUserInfo,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchMakingUserInfo,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchMakingUserInfoLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchMakingUserInfo,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchMakingUserInfo,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingGroupCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingGroupCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingGroupCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingGroupCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingGroupCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingGroupCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingUserDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingUserData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingUserData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingUserDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingUserData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingUserData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountItemsUserDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountItemsUserData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountItemsUserData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMountItemsUserDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountItemsUserData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MountItemsUserData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingModeRankLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingModeRank,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingModeRank,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingModeRankLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingModeRank,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingModeRank,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingModeLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MatchmakingMode,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MatchmakingMode,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingModeLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MatchmakingMode,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MatchmakingMode,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingLayoutCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingLayoutCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingLayoutCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMatchmakingLayoutCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingLayoutCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(MatchmakingLayoutCC,true),true,1),new OptionalCodecDecorator(local4));
    }

    public function stop(param1:OSGi) : void {
    }
  }
}
