package projects.tanks.client.tanksservices.osgi {
  import _codec.projects.tanks.client.tanksservices.model.clientrestarttime.CodecOnceADayActionCC;
  import _codec.projects.tanks.client.tanksservices.model.clientrestarttime.VectorCodecOnceADayActionCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.formatbattle.CodecEquipmentConstraintsCC;
  import _codec.projects.tanks.client.tanksservices.model.formatbattle.CodecEquipmentConstraintsModeInfo;
  import _codec.projects.tanks.client.tanksservices.model.formatbattle.VectorCodecEquipmentConstraintsCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.formatbattle.VectorCodecEquipmentConstraintsModeInfoLevel1;
  import _codec.projects.tanks.client.tanksservices.model.listener.CodecUserNotifierCC;
  import _codec.projects.tanks.client.tanksservices.model.listener.VectorCodecUserNotifierCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.logging.CodecUserActionsLoggerCC;
  import _codec.projects.tanks.client.tanksservices.model.logging.VectorCodecUserActionsLoggerCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.logging.battlelist.CodecBattleSelectAction;
  import _codec.projects.tanks.client.tanksservices.model.logging.battlelist.VectorCodecBattleSelectActionLevel1;
  import _codec.projects.tanks.client.tanksservices.model.logging.gamescreen.CodecGameScreen;
  import _codec.projects.tanks.client.tanksservices.model.logging.gamescreen.VectorCodecGameScreenLevel1;
  import _codec.projects.tanks.client.tanksservices.model.logging.garage.CodecGarageAction;
  import _codec.projects.tanks.client.tanksservices.model.logging.garage.VectorCodecGarageActionLevel1;
  import _codec.projects.tanks.client.tanksservices.model.logging.payment.CodecPaymentAction;
  import _codec.projects.tanks.client.tanksservices.model.logging.payment.VectorCodecPaymentActionLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.CodecAbstractNotifier;
  import _codec.projects.tanks.client.tanksservices.model.notifier.VectorCodecAbstractNotifierLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.battle.CodecBattleNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.battle.VectorCodecBattleNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.online.CodecOnlineNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.online.VectorCodecOnlineNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.premium.CodecPremiumNotifierCC;
  import _codec.projects.tanks.client.tanksservices.model.notifier.premium.VectorCodecPremiumNotifierCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.rank.CodecRankNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.rank.VectorCodecRankNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.referrals.CodecReferralNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.referrals.VectorCodecReferralNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.socialnetworks.CodecSNUidNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.socialnetworks.VectorCodecSNUidNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.notifier.uid.CodecUidNotifierData;
  import _codec.projects.tanks.client.tanksservices.model.notifier.uid.VectorCodecUidNotifierDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.proabonementnotifier.CodecProAbonementNotifierCC;
  import _codec.projects.tanks.client.tanksservices.model.proabonementnotifier.VectorCodecProAbonementNotifierCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.rankloader.CodecRankInfo;
  import _codec.projects.tanks.client.tanksservices.model.rankloader.CodecRankLoaderCC;
  import _codec.projects.tanks.client.tanksservices.model.rankloader.VectorCodecRankInfoLevel1;
  import _codec.projects.tanks.client.tanksservices.model.rankloader.VectorCodecRankLoaderCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.reconnect.CodecReconnectCC;
  import _codec.projects.tanks.client.tanksservices.model.reconnect.CodecRemoteEndpointData;
  import _codec.projects.tanks.client.tanksservices.model.reconnect.VectorCodecReconnectCCLevel1;
  import _codec.projects.tanks.client.tanksservices.model.reconnect.VectorCodecRemoteEndpointDataLevel1;
  import _codec.projects.tanks.client.tanksservices.model.uidcheck.CodecUidCheckCC;
  import _codec.projects.tanks.client.tanksservices.model.uidcheck.VectorCodecUidCheckCCLevel1;
  import _codec.projects.tanks.client.tanksservices.types.battle.CodecBattleInfoData;
  import _codec.projects.tanks.client.tanksservices.types.battle.VectorCodecBattleInfoDataLevel1;
  import alternativa.osgi.OSGi;
  import alternativa.osgi.bundle.IBundleActivator;
  import alternativa.protocol.ICodec;
  import alternativa.protocol.IProtocol;
  import alternativa.protocol.codec.OptionalCodecDecorator;
  import alternativa.protocol.info.CollectionCodecInfo;
  import alternativa.protocol.info.EnumCodecInfo;
  import alternativa.protocol.info.TypeCodecInfo;
  import alternativa.types.Long;
  import platform.client.fp10.core.registry.ModelRegistry;
  import projects.tanks.client.tanksservices.model.clientrestarttime.OnceADayActionCC;
  import projects.tanks.client.tanksservices.model.formatbattle.EquipmentConstraintsCC;
  import projects.tanks.client.tanksservices.model.formatbattle.EquipmentConstraintsModeInfo;
  import projects.tanks.client.tanksservices.model.listener.UserNotifierCC;
  import projects.tanks.client.tanksservices.model.logging.UserActionsLoggerCC;
  import projects.tanks.client.tanksservices.model.logging.battlelist.BattleSelectAction;
  import projects.tanks.client.tanksservices.model.logging.gamescreen.GameScreen;
  import projects.tanks.client.tanksservices.model.logging.garage.GarageAction;
  import projects.tanks.client.tanksservices.model.logging.payment.PaymentAction;
  import projects.tanks.client.tanksservices.model.notifier.AbstractNotifier;
  import projects.tanks.client.tanksservices.model.notifier.battle.BattleNotifierData;
  import projects.tanks.client.tanksservices.model.notifier.online.OnlineNotifierData;
  import projects.tanks.client.tanksservices.model.notifier.premium.PremiumNotifierCC;
  import projects.tanks.client.tanksservices.model.notifier.rank.RankNotifierData;
  import projects.tanks.client.tanksservices.model.notifier.referrals.ReferralNotifierData;
  import projects.tanks.client.tanksservices.model.notifier.socialnetworks.SNUidNotifierData;
  import projects.tanks.client.tanksservices.model.notifier.uid.UidNotifierData;
  import projects.tanks.client.tanksservices.model.proabonementnotifier.ProAbonementNotifierCC;
  import projects.tanks.client.tanksservices.model.rankloader.RankInfo;
  import projects.tanks.client.tanksservices.model.rankloader.RankLoaderCC;
  import projects.tanks.client.tanksservices.model.reconnect.ReconnectCC;
  import projects.tanks.client.tanksservices.model.reconnect.RemoteEndpointData;
  import projects.tanks.client.tanksservices.model.uidcheck.UidCheckCC;
  import projects.tanks.client.tanksservices.types.battle.BattleInfoData;

  public class Activator implements IBundleActivator {
    public static var osgi:OSGi;

    public function Activator() {
      super();
    }

    public function start(param1:OSGi) : void {
      var local4:ICodec = null;
      osgi = param1;
      var local2:ModelRegistry = ModelRegistry(OSGi.getInstance().getService(ModelRegistry));
      local2.register(Long.getLong(904565121,-177943041),Long.getLong(1976915722,-215540987));
      local2.register(Long.getLong(904565121,-177943041),Long.getLong(617960803,1927590436));
      local2.register(Long.getLong(904565121,-177943041),Long.getLong(534256502,-1360731802));
      local2.register(Long.getLong(467887314,-1426971041),Long.getLong(1815033699,-407485089));
      local2.register(Long.getLong(302389563,-1379937773),Long.getLong(1172025171,225736801));
      local2.register(Long.getLong(60229216,350352129),Long.getLong(1290751540,-2034560678));
      local2.register(Long.getLong(1904649067,-739596764),Long.getLong(474883635,-1307823504));
      local2.register(Long.getLong(1741772027,-10049568),Long.getLong(1110422483,-372446840));
      local2.register(Long.getLong(990863444,376077627),Long.getLong(290132373,74250398));
      local2.register(Long.getLong(1634466802,-928935342),Long.getLong(1929134425,15611068));
      local2.register(Long.getLong(1511581132,-1911657689),Long.getLong(1048793908,1208118313));
      local2.register(Long.getLong(1511581132,-1911657689),Long.getLong(1752522899,-540791768));
      local2.register(Long.getLong(1511581132,-1911657689),Long.getLong(1594746948,-1573293870));
      local2.register(Long.getLong(1543089237,611543143),Long.getLong(317069682,-1647554367));
      var local3:IProtocol = IProtocol(osgi.getService(IProtocol));
      local4 = new CodecOnceADayActionCC();
      local3.registerCodec(new TypeCodecInfo(OnceADayActionCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(OnceADayActionCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecEquipmentConstraintsCC();
      local3.registerCodec(new TypeCodecInfo(EquipmentConstraintsCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(EquipmentConstraintsCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecEquipmentConstraintsModeInfo();
      local3.registerCodec(new TypeCodecInfo(EquipmentConstraintsModeInfo,false),local4);
      local3.registerCodec(new TypeCodecInfo(EquipmentConstraintsModeInfo,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUserNotifierCC();
      local3.registerCodec(new TypeCodecInfo(UserNotifierCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(UserNotifierCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUserActionsLoggerCC();
      local3.registerCodec(new TypeCodecInfo(UserActionsLoggerCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(UserActionsLoggerCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleSelectAction();
      local3.registerCodec(new EnumCodecInfo(BattleSelectAction,false),local4);
      local3.registerCodec(new EnumCodecInfo(BattleSelectAction,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGameScreen();
      local3.registerCodec(new EnumCodecInfo(GameScreen,false),local4);
      local3.registerCodec(new EnumCodecInfo(GameScreen,true),new OptionalCodecDecorator(local4));
      local4 = new CodecGarageAction();
      local3.registerCodec(new EnumCodecInfo(GarageAction,false),local4);
      local3.registerCodec(new EnumCodecInfo(GarageAction,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPaymentAction();
      local3.registerCodec(new EnumCodecInfo(PaymentAction,false),local4);
      local3.registerCodec(new EnumCodecInfo(PaymentAction,true),new OptionalCodecDecorator(local4));
      local4 = new CodecAbstractNotifier();
      local3.registerCodec(new TypeCodecInfo(AbstractNotifier,false),local4);
      local3.registerCodec(new TypeCodecInfo(AbstractNotifier,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleNotifierData();
      local3.registerCodec(new TypeCodecInfo(BattleNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecOnlineNotifierData();
      local3.registerCodec(new TypeCodecInfo(OnlineNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(OnlineNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPremiumNotifierCC();
      local3.registerCodec(new TypeCodecInfo(PremiumNotifierCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PremiumNotifierCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRankNotifierData();
      local3.registerCodec(new TypeCodecInfo(RankNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(RankNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecReferralNotifierData();
      local3.registerCodec(new TypeCodecInfo(ReferralNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(ReferralNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecSNUidNotifierData();
      local3.registerCodec(new TypeCodecInfo(SNUidNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(SNUidNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUidNotifierData();
      local3.registerCodec(new TypeCodecInfo(UidNotifierData,false),local4);
      local3.registerCodec(new TypeCodecInfo(UidNotifierData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecProAbonementNotifierCC();
      local3.registerCodec(new TypeCodecInfo(ProAbonementNotifierCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ProAbonementNotifierCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRankInfo();
      local3.registerCodec(new TypeCodecInfo(RankInfo,false),local4);
      local3.registerCodec(new TypeCodecInfo(RankInfo,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRankLoaderCC();
      local3.registerCodec(new TypeCodecInfo(RankLoaderCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(RankLoaderCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecReconnectCC();
      local3.registerCodec(new TypeCodecInfo(ReconnectCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ReconnectCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRemoteEndpointData();
      local3.registerCodec(new TypeCodecInfo(RemoteEndpointData,false),local4);
      local3.registerCodec(new TypeCodecInfo(RemoteEndpointData,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUidCheckCC();
      local3.registerCodec(new TypeCodecInfo(UidCheckCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(UidCheckCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleInfoData();
      local3.registerCodec(new TypeCodecInfo(BattleInfoData,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleInfoData,true),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecOnceADayActionCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnceADayActionCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnceADayActionCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecOnceADayActionCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnceADayActionCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnceADayActionCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecEquipmentConstraintsCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecEquipmentConstraintsCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecEquipmentConstraintsModeInfoLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsModeInfo,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsModeInfo,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecEquipmentConstraintsModeInfoLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsModeInfo,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(EquipmentConstraintsModeInfo,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserNotifierCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserNotifierCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserNotifierCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserNotifierCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserNotifierCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserNotifierCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserActionsLoggerCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserActionsLoggerCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserActionsLoggerCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserActionsLoggerCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserActionsLoggerCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserActionsLoggerCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleSelectActionLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSelectAction,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSelectAction,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleSelectActionLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSelectAction,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSelectAction,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGameScreenLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GameScreen,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GameScreen,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGameScreenLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GameScreen,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GameScreen,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageActionLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GarageAction,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GarageAction,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecGarageActionLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GarageAction,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(GarageAction,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPaymentActionLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(PaymentAction,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(PaymentAction,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPaymentActionLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(PaymentAction,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(PaymentAction,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAbstractNotifierLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AbstractNotifier,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AbstractNotifier,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecAbstractNotifierLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AbstractNotifier,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(AbstractNotifier,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecOnlineNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnlineNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnlineNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecOnlineNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnlineNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(OnlineNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPremiumNotifierCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumNotifierCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumNotifierCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPremiumNotifierCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumNotifierCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PremiumNotifierCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecReferralNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReferralNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReferralNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecReferralNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReferralNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReferralNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecSNUidNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(SNUidNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(SNUidNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecSNUidNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(SNUidNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(SNUidNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUidNotifierDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidNotifierData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidNotifierData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUidNotifierDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidNotifierData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidNotifierData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecProAbonementNotifierCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementNotifierCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementNotifierCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecProAbonementNotifierCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementNotifierCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ProAbonementNotifierCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankInfoLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankInfo,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankInfo,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankInfoLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankInfo,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankInfo,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankLoaderCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankLoaderCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankLoaderCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRankLoaderCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankLoaderCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RankLoaderCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecReconnectCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReconnectCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReconnectCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecReconnectCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReconnectCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ReconnectCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRemoteEndpointDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RemoteEndpointData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RemoteEndpointData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRemoteEndpointDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RemoteEndpointData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(RemoteEndpointData,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUidCheckCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidCheckCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidCheckCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUidCheckCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidCheckCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UidCheckCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoDataLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoData,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoData,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleInfoDataLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoData,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleInfoData,true),true,1),new OptionalCodecDecorator(local4));
    }

    public function stop(param1:OSGi) : void {
    }
  }
}
