package projects.tanks.client.garage.models.item.properties {
  public class ItemProperty {
    public static const HULL_ARMOR:ItemProperty = new ItemProperty(0,"HULL_ARMOR");
    public static const HULL_SPEED:ItemProperty = new ItemProperty(1,"HULL_SPEED");
    public static const HULL_SIDE_ACCELERATION:ItemProperty = new ItemProperty(2,"HULL_SIDE_ACCELERATION");
    public static const HULL_TURN_SPEED:ItemProperty = new ItemProperty(3,"HULL_TURN_SPEED");
    public static const HULL_TURN_ACCELERATION:ItemProperty = new ItemProperty(4,"HULL_TURN_ACCELERATION");
    public static const HULL_REVERSE_TURN_ACCELERATION:ItemProperty = new ItemProperty(5,"HULL_REVERSE_TURN_ACCELERATION");
    public static const HULL_TURN_STABILIZATION_ACCELERATION:ItemProperty = new ItemProperty(6,"HULL_TURN_STABILIZATION_ACCELERATION");
    public static const HULL_ACCELERATION:ItemProperty = new ItemProperty(7,"HULL_ACCELERATION");
    public static const HULL_REVERSE_ACCELERATION:ItemProperty = new ItemProperty(8,"HULL_REVERSE_ACCELERATION");
    public static const HULL_MASS:ItemProperty = new ItemProperty(9,"HULL_MASS");
    public static const TURRET_TURN_SPEED:ItemProperty = new ItemProperty(10,"TURRET_TURN_SPEED");
    public static const TURRET_ROTATION_ACCELERATION:ItemProperty = new ItemProperty(11,"TURRET_ROTATION_ACCELERATION");
    public static const INITIAL_TURRET_ANGLE:ItemProperty = new ItemProperty(12,"INITIAL_TURRET_ANGLE");
    public static const IMPACT_FORCE:ItemProperty = new ItemProperty(13,"IMPACT_FORCE");
    public static const DAMAGE_FROM:ItemProperty = new ItemProperty(14,"DAMAGE_FROM");
    public static const DAMAGE_TO:ItemProperty = new ItemProperty(15,"DAMAGE_TO");
    public static const DAMAGE_PER_SECOND:ItemProperty = new ItemProperty(16,"DAMAGE_PER_SECOND");
    public static const WEAPON_RELOAD_TIME:ItemProperty = new ItemProperty(17,"WEAPON_RELOAD_TIME");
    public static const WEAPON_CHARGING_TIME:ItemProperty = new ItemProperty(18,"WEAPON_CHARGING_TIME");
    public static const WEAPON_WEAKENING_COEFF:ItemProperty = new ItemProperty(19,"WEAPON_WEAKENING_COEFF");
    public static const FIREBIRD_RESISTANCE:ItemProperty = new ItemProperty(20,"FIREBIRD_RESISTANCE");
    public static const SMOKY_RESISTANCE:ItemProperty = new ItemProperty(21,"SMOKY_RESISTANCE");
    public static const TWINS_RESISTANCE:ItemProperty = new ItemProperty(22,"TWINS_RESISTANCE");
    public static const RAILGUN_RESISTANCE:ItemProperty = new ItemProperty(23,"RAILGUN_RESISTANCE");
    public static const ISIS_RESISTANCE:ItemProperty = new ItemProperty(24,"ISIS_RESISTANCE");
    public static const MINE_RESISTANCE:ItemProperty = new ItemProperty(25,"MINE_RESISTANCE");
    public static const THUNDER_RESISTANCE:ItemProperty = new ItemProperty(26,"THUNDER_RESISTANCE");
    public static const FREEZE_RESISTANCE:ItemProperty = new ItemProperty(27,"FREEZE_RESISTANCE");
    public static const RICOCHET_RESISTANCE:ItemProperty = new ItemProperty(28,"RICOCHET_RESISTANCE");
    public static const SHAFT_RESISTANCE:ItemProperty = new ItemProperty(29,"SHAFT_RESISTANCE");
    public static const MACHINE_GUN_RESISTANCE:ItemProperty = new ItemProperty(30,"MACHINE_GUN_RESISTANCE");
    public static const SHOTGUN_RESISTANCE:ItemProperty = new ItemProperty(31,"SHOTGUN_RESISTANCE");
    public static const ROCKET_LAUNCHER_RESISTANCE:ItemProperty = new ItemProperty(32,"ROCKET_LAUNCHER_RESISTANCE");
    public static const ARTILLERY_RESISTANCE:ItemProperty = new ItemProperty(33,"ARTILLERY_RESISTANCE");
    public static const TERMINATOR_RESISTANCE:ItemProperty = new ItemProperty(34,"TERMINATOR_RESISTANCE");
    public static const GAUSS_RESISTANCE:ItemProperty = new ItemProperty(35,"GAUSS_RESISTANCE");
    public static const ALL_RESISTANCE:ItemProperty = new ItemProperty(36,"ALL_RESISTANCE");
    public static const SHAFT_AIMING_MODE_MIN_DAMAGE:ItemProperty = new ItemProperty(37,"SHAFT_AIMING_MODE_MIN_DAMAGE");
    public static const SHAFT_AIMING_MODE_MAX_DAMAGE:ItemProperty = new ItemProperty(38,"SHAFT_AIMING_MODE_MAX_DAMAGE");
    public static const SHAFT_VERTICAL_TARGETING_SPEED:ItemProperty = new ItemProperty(39,"SHAFT_VERTICAL_TARGETING_SPEED");
    public static const SHAFT_HORIZONTAL_TARGETING_SPEED:ItemProperty = new ItemProperty(40,"SHAFT_HORIZONTAL_TARGETING_SPEED");
    public static const SHAFT_AIMING_MODE_CHARGE_RATE:ItemProperty = new ItemProperty(41,"SHAFT_AIMING_MODE_CHARGE_RATE");
    public static const SHAFT_AIMED_SHOT_IMPACT:ItemProperty = new ItemProperty(42,"SHAFT_AIMED_SHOT_IMPACT");
    public static const SHAFT_ROTATION_DECELERATION_COEFF:ItemProperty = new ItemProperty(43,"SHAFT_ROTATION_DECELERATION_COEFF");
    public static const SHAFT_FAST_SHOT_ENERGY:ItemProperty = new ItemProperty(44,"SHAFT_FAST_SHOT_ENERGY");
    public static const SHAFT_MIN_AIMED_SHOT_ENERGY:ItemProperty = new ItemProperty(45,"SHAFT_MIN_AIMED_SHOT_ENERGY");
    public static const WEAPON_CHARGE_RATE:ItemProperty = new ItemProperty(46,"WEAPON_CHARGE_RATE");
    public static const WEAPON_KICKBACK:ItemProperty = new ItemProperty(47,"WEAPON_KICKBACK");
    public static const WEAPON_MIN_DAMAGE_PERCENT:ItemProperty = new ItemProperty(48,"WEAPON_MIN_DAMAGE_PERCENT");
    public static const WEAPON_MIN_DAMAGE_RADIUS:ItemProperty = new ItemProperty(49,"WEAPON_MIN_DAMAGE_RADIUS");
    public static const WEAPON_MAX_DAMAGE_RADIUS:ItemProperty = new ItemProperty(50,"WEAPON_MAX_DAMAGE_RADIUS");
    public static const SHOT_RANGE:ItemProperty = new ItemProperty(51,"SHOT_RANGE");
    public static const MAX_CRITICAL_HIT_CHANCE:ItemProperty = new ItemProperty(52,"MAX_CRITICAL_HIT_CHANCE");
    public static const START_CRITICAL_HIT_CHANCE:ItemProperty = new ItemProperty(53,"START_CRITICAL_HIT_CHANCE");
    public static const AFTER_CRIT_CRITICAL_HIT_CHANCE:ItemProperty = new ItemProperty(54,"AFTER_CRIT_CRITICAL_HIT_CHANCE");
    public static const CRITICAL_CHANCE_DELTA:ItemProperty = new ItemProperty(55,"CRITICAL_CHANCE_DELTA");
    public static const CRITICAL_HIT_CHANCE:ItemProperty = new ItemProperty(56,"CRITICAL_HIT_CHANCE");
    public static const CRITICAL_HIT_DAMAGE:ItemProperty = new ItemProperty(57,"CRITICAL_HIT_DAMAGE");
    public static const SPLASH_DAMAGE_RADIUS:ItemProperty = new ItemProperty(58,"SPLASH_DAMAGE_RADIUS");
    public static const RADIUS_OF_MAX_SPLASH_DAMAGE:ItemProperty = new ItemProperty(59,"RADIUS_OF_MAX_SPLASH_DAMAGE");
    public static const MIN_SPLASH_DAMAGE_PERCENT:ItemProperty = new ItemProperty(60,"MIN_SPLASH_DAMAGE_PERCENT");
    public static const SPLASH_DAMAGE_IMPACT:ItemProperty = new ItemProperty(61,"SPLASH_DAMAGE_IMPACT");
    public static const RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE:ItemProperty = new ItemProperty(62,"RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE");
    public static const FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT:ItemProperty = new ItemProperty(63,"FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT");
    public static const WEAPON_DISCHARGE_RATE:ItemProperty = new ItemProperty(64,"WEAPON_DISCHARGE_RATE");
    public static const DAMAGE_PER_PERIOD:ItemProperty = new ItemProperty(65,"DAMAGE_PER_PERIOD");
    public static const ISIS_HEALING_PER_PERIOD:ItemProperty = new ItemProperty(66,"ISIS_HEALING_PER_PERIOD");
    public static const ISIS_INCREASE_TARGET_TEMPERATURE_PER_TICK:ItemProperty = new ItemProperty(67,"ISIS_INCREASE_TARGET_TEMPERATURE_PER_TICK");
    public static const ISIS_DECREASE_TARGET_TEMPERATURE_PER_TICK:ItemProperty = new ItemProperty(68,"ISIS_DECREASE_TARGET_TEMPERATURE_PER_TICK");
    public static const ISIS_DISCHARGE_SPEED_HEALING:ItemProperty = new ItemProperty(69,"ISIS_DISCHARGE_SPEED_HEALING");
    public static const ISIS_DISCHARGE_SPEED_IDLE:ItemProperty = new ItemProperty(70,"ISIS_DISCHARGE_SPEED_IDLE");
    public static const FLAME_TEMPERATURE_LIMIT:ItemProperty = new ItemProperty(71,"FLAME_TEMPERATURE_LIMIT");
    public static const HEAT_PER_PERIOD:ItemProperty = new ItemProperty(72,"HEAT_PER_PERIOD");
    public static const ENERGY_PER_SHOT:ItemProperty = new ItemProperty(73,"ENERGY_PER_SHOT");
    public static const MACHINE_GUN_SELF_TEMPERATURE_INCREASE_PER_SECOND:ItemProperty = new ItemProperty(74,"MACHINE_GUN_SELF_TEMPERATURE_INCREASE_PER_SECOND");
    public static const MACHINE_GUN_SPIN_UP_TIME_SECOND:ItemProperty = new ItemProperty(75,"MACHINE_GUN_SPIN_UP_TIME_SECOND");
    public static const MACHINE_GUN_SPIN_DOWN_TIME_SECOND:ItemProperty = new ItemProperty(76,"MACHINE_GUN_SPIN_DOWN_TIME_SECOND");
    public static const MACHINE_GUN_WEAPON_TURN_DECELERATION_COEFF:ItemProperty = new ItemProperty(77,"MACHINE_GUN_WEAPON_TURN_DECELERATION_COEFF");
    public static const MACHINE_GUN_TEMPERATURE_HITTING_TIME_SECOND:ItemProperty = new ItemProperty(78,"MACHINE_GUN_TEMPERATURE_HITTING_TIME_SECOND");
    public static const MACHINE_GUN_OVERHEAT_DAMAGE_COEFF:ItemProperty = new ItemProperty(79,"MACHINE_GUN_OVERHEAT_DAMAGE_COEFF");
    public static const MACHINE_GUN_POWER_WHEN_TANK_TEMPERATURE_START_INCREASE:ItemProperty = new ItemProperty(80,"MACHINE_GUN_POWER_WHEN_TANK_TEMPERATURE_START_INCREASE");
    public static const ELLIPTIC_CONE_VERTICAL_ANGLE:ItemProperty = new ItemProperty(81,"ELLIPTIC_CONE_VERTICAL_ANGLE");
    public static const ELLIPTIC_CONE_HORIZONTAL_ANGLE:ItemProperty = new ItemProperty(82,"ELLIPTIC_CONE_HORIZONTAL_ANGLE");
    public static const SHOTGUN_MAGAZINE_SIZE:ItemProperty = new ItemProperty(83,"SHOTGUN_MAGAZINE_SIZE");
    public static const SHOTGUN_PELLET_COUNT:ItemProperty = new ItemProperty(84,"SHOTGUN_PELLET_COUNT");
    public static const MAGAZINE_RELOAD_TIME:ItemProperty = new ItemProperty(85,"MAGAZINE_RELOAD_TIME");
    public static const DAMAGE_PER_HIT:ItemProperty = new ItemProperty(86,"DAMAGE_PER_HIT");
    public static const DISCHARGE_SPEED:ItemProperty = new ItemProperty(87,"DISCHARGE_SPEED");
    public static const CONE_ANGLE:ItemProperty = new ItemProperty(88,"CONE_ANGLE");
    public static const FREEZE_PER_TICK:ItemProperty = new ItemProperty(89,"FREEZE_PER_TICK");
    public static const WEAPON_ANGLE_UP:ItemProperty = new ItemProperty(90,"WEAPON_ANGLE_UP");
    public static const WEAPON_ANGLE_DOWN:ItemProperty = new ItemProperty(91,"WEAPON_ANGLE_DOWN");
    public static const ROCKET_ANGULAR_VELOCITY:ItemProperty = new ItemProperty(92,"ROCKET_ANGULAR_VELOCITY");
    public static const SALVO_AIMING_TIME:ItemProperty = new ItemProperty(93,"SALVO_AIMING_TIME");
    public static const SALVO_AIMING_GRACE_PERIOD:ItemProperty = new ItemProperty(94,"SALVO_AIMING_GRACE_PERIOD");
    public static const TIME_BETWEEN_SHOTS_OF_SALVO:ItemProperty = new ItemProperty(95,"TIME_BETWEEN_SHOTS_OF_SALVO");
    public static const SALVO_RELOAD_TIME:ItemProperty = new ItemProperty(96,"SALVO_RELOAD_TIME");
    public static const SALVO_SIZE:ItemProperty = new ItemProperty(97,"SALVO_SIZE");
    public static const SHELL_SPEED:ItemProperty = new ItemProperty(98,"SHELL_SPEED");
    public static const SHELL_RADIUS:ItemProperty = new ItemProperty(99,"SHELL_RADIUS");
    public static const MIN_SHELL_SPEED:ItemProperty = new ItemProperty(100,"MIN_SHELL_SPEED");
    public static const MAX_SHELL_SPEED:ItemProperty = new ItemProperty(101,"MAX_SHELL_SPEED");
    public static const SHELL_BOOST_PHASE_DURATION:ItemProperty = new ItemProperty(102,"SHELL_BOOST_PHASE_DURATION");
    public static const SHELL_SPEEDS_COUNT:ItemProperty = new ItemProperty(103,"SHELL_SPEEDS_COUNT");
    public static const SHELL_GRAVITY_COEF:ItemProperty = new ItemProperty(104,"SHELL_GRAVITY_COEF");
    public static const MAX_RICOCHET_COUNT:ItemProperty = new ItemProperty(105,"MAX_RICOCHET_COUNT");
    public static const SECONDARY_WEAPON_KICKBACK:ItemProperty = new ItemProperty(106,"SECONDARY_WEAPON_KICKBACK");
    public static const SECONDARY_DAMAGE_FROM:ItemProperty = new ItemProperty(107,"SECONDARY_DAMAGE_FROM");
    public static const SECONDARY_DAMAGE_TO:ItemProperty = new ItemProperty(108,"SECONDARY_DAMAGE_TO");
    public static const HIGHLIGHTING_DISTANCE:ItemProperty = new ItemProperty(109,"HIGHLIGHTING_DISTANCE");
    public static const DRONE_RELOAD:ItemProperty = new ItemProperty(110,"DRONE_RELOAD");
    public static const DRONE_REPAIR_HEALTH:ItemProperty = new ItemProperty(111,"DRONE_REPAIR_HEALTH");
    public static const DRONE_REPAIR_RADIUS:ItemProperty = new ItemProperty(112,"DRONE_REPAIR_RADIUS");
    public static const DRONE_INVENTORY:ItemProperty = new ItemProperty(113,"DRONE_INVENTORY");
    public static const DRONE_INVENTORY_ADD:ItemProperty = new ItemProperty(114,"DRONE_INVENTORY_ADD");
    public static const DRONE_BONUS_ADD:ItemProperty = new ItemProperty(115,"DRONE_BONUS_ADD");
    public static const DRONE_FIRST_AID_BONUS_ADD:ItemProperty = new ItemProperty(116,"DRONE_FIRST_AID_BONUS_ADD");
    public static const DRONE_OVERDRIVE_BOOST:ItemProperty = new ItemProperty(117,"DRONE_OVERDRIVE_BOOST");
    public static const DRONE_INVENTORY_RADIUS:ItemProperty = new ItemProperty(118,"DRONE_INVENTORY_RADIUS");
    public static const DRONE_COOLDOWN_RADIUS:ItemProperty = new ItemProperty(119,"DRONE_COOLDOWN_RADIUS");
    public static const DRONE_DEFEND:ItemProperty = new ItemProperty(120,"DRONE_DEFEND");
    public static const DRONE_ARMOR_BOOST:ItemProperty = new ItemProperty(121,"DRONE_ARMOR_BOOST");
    public static const DRONE_MINE:ItemProperty = new ItemProperty(122,"DRONE_MINE");
    public static const DRONE_ADDITIONAL_MINES:ItemProperty = new ItemProperty(123,"DRONE_ADDITIONAL_MINES");
    public static const DRONE_MINES_ACTIVATION_DELAY:ItemProperty = new ItemProperty(124,"DRONE_MINES_ACTIVATION_DELAY");
    public static const DRONE_INVENTORY_COOLDOWN_BOOST:ItemProperty = new ItemProperty(125,"DRONE_INVENTORY_COOLDOWN_BOOST");
    public static const DRONE_MINES_PLACEMENT_RADIUS:ItemProperty = new ItemProperty(126,"DRONE_MINES_PLACEMENT_RADIUS");
    public static const DRONE_POWER_BOOST:ItemProperty = new ItemProperty(127,"DRONE_POWER_BOOST");
    public static const DRONE_POWER_DURATION:ItemProperty = new ItemProperty(128,"DRONE_POWER_DURATION");
    public static const DRONE_CRITICAL_HEALTH:ItemProperty = new ItemProperty(129,"DRONE_CRITICAL_HEALTH");
    public static const DRONE_CONSTANT_ARMOR_PERCENT:ItemProperty = new ItemProperty(130,"DRONE_CONSTANT_ARMOR_PERCENT");
    public static const DRONE_CONSTANT_POWER_PERCENT:ItemProperty = new ItemProperty(131,"DRONE_CONSTANT_POWER_PERCENT");
    public static const ULTIMATE_HEAL_HP:ItemProperty = new ItemProperty(132,"ULTIMATE_HEAL_HP");
    public static const DEVICE_TEMPERATURE_NORMALIZATION:ItemProperty = new ItemProperty(133,"DEVICE_TEMPERATURE_NORMALIZATION");
    public static const DEVICE_BONUS_ENERGY_ON_KILL:ItemProperty = new ItemProperty(134,"DEVICE_BONUS_ENERGY_ON_KILL");
    public static const DEVICE_HEAT_PER_PELLET:ItemProperty = new ItemProperty(135,"DEVICE_HEAT_PER_PELLET");
    public static const DEVICE_SMOKY_TEMPERATURE_DELTA_ON_CRITICAL:ItemProperty = new ItemProperty(136,"DEVICE_SMOKY_TEMPERATURE_DELTA_ON_CRITICAL");
    public static const DEVICE_TARGET_HEAT_DELTA_ON_SELF_OVERHEAT:ItemProperty = new ItemProperty(137,"DEVICE_TARGET_HEAT_DELTA_ON_SELF_OVERHEAT");
    public static const ULTIMATE_CHARGE_PER_SEC:ItemProperty = new ItemProperty(138,"ULTIMATE_CHARGE_PER_SEC");
    public static const ULTIMATE_CHARGE_PER_SCORE_POINT:ItemProperty = new ItemProperty(139,"ULTIMATE_CHARGE_PER_SCORE_POINT");
    public static const ULTIMATE_SCORE_COOLDOWN_SEC:ItemProperty = new ItemProperty(140,"ULTIMATE_SCORE_COOLDOWN_SEC");
    public static const ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC:ItemProperty = new ItemProperty(141,"ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC");
    public static const GAUSS_AIMED_SHOT_IMPACT:ItemProperty = new ItemProperty(142,"GAUSS_AIMED_SHOT_IMPACT");
    public static const GAUSS_AIMED_SPLASH_DAMAGE_RADIUS:ItemProperty = new ItemProperty(143,"GAUSS_AIMED_SPLASH_DAMAGE_RADIUS");
    public static const GAUSS_AIMED_RADIUS_OF_MAX_SPLASH_DAMAGE:ItemProperty = new ItemProperty(144,"GAUSS_AIMED_RADIUS_OF_MAX_SPLASH_DAMAGE");
    public static const GAUSS_AIMED_MIN_SPLASH_DAMAGE_PERCENT:ItemProperty = new ItemProperty(145,"GAUSS_AIMED_MIN_SPLASH_DAMAGE_PERCENT");
    public static const GAUSS_AIMED_SPLASH_DAMAGE_IMPACT:ItemProperty = new ItemProperty(146,"GAUSS_AIMED_SPLASH_DAMAGE_IMPACT");
    public static const GAUSS_AIMED_RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE:ItemProperty = new ItemProperty(147,"GAUSS_AIMED_RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE");
    public static const GAUSS_AIMED_FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT:ItemProperty = new ItemProperty(148,"GAUSS_AIMED_FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT");

    private var _value:int;
    private var _name:String;

    public function ItemProperty(param1:int, param2:String) {
      super();
      this._value = param1;
      this._name = param2;
    }

    public static function get values() : Vector.<ItemProperty> {
      var local1:Vector.<ItemProperty> = new Vector.<ItemProperty>();
      local1.push(HULL_ARMOR);
      local1.push(HULL_SPEED);
      local1.push(HULL_SIDE_ACCELERATION);
      local1.push(HULL_TURN_SPEED);
      local1.push(HULL_TURN_ACCELERATION);
      local1.push(HULL_REVERSE_TURN_ACCELERATION);
      local1.push(HULL_TURN_STABILIZATION_ACCELERATION);
      local1.push(HULL_ACCELERATION);
      local1.push(HULL_REVERSE_ACCELERATION);
      local1.push(HULL_MASS);
      local1.push(TURRET_TURN_SPEED);
      local1.push(TURRET_ROTATION_ACCELERATION);
      local1.push(INITIAL_TURRET_ANGLE);
      local1.push(IMPACT_FORCE);
      local1.push(DAMAGE_FROM);
      local1.push(DAMAGE_TO);
      local1.push(DAMAGE_PER_SECOND);
      local1.push(WEAPON_RELOAD_TIME);
      local1.push(WEAPON_CHARGING_TIME);
      local1.push(WEAPON_WEAKENING_COEFF);
      local1.push(FIREBIRD_RESISTANCE);
      local1.push(SMOKY_RESISTANCE);
      local1.push(TWINS_RESISTANCE);
      local1.push(RAILGUN_RESISTANCE);
      local1.push(ISIS_RESISTANCE);
      local1.push(MINE_RESISTANCE);
      local1.push(THUNDER_RESISTANCE);
      local1.push(FREEZE_RESISTANCE);
      local1.push(RICOCHET_RESISTANCE);
      local1.push(SHAFT_RESISTANCE);
      local1.push(MACHINE_GUN_RESISTANCE);
      local1.push(SHOTGUN_RESISTANCE);
      local1.push(ROCKET_LAUNCHER_RESISTANCE);
      local1.push(ARTILLERY_RESISTANCE);
      local1.push(TERMINATOR_RESISTANCE);
      local1.push(GAUSS_RESISTANCE);
      local1.push(ALL_RESISTANCE);
      local1.push(SHAFT_AIMING_MODE_MIN_DAMAGE);
      local1.push(SHAFT_AIMING_MODE_MAX_DAMAGE);
      local1.push(SHAFT_VERTICAL_TARGETING_SPEED);
      local1.push(SHAFT_HORIZONTAL_TARGETING_SPEED);
      local1.push(SHAFT_AIMING_MODE_CHARGE_RATE);
      local1.push(SHAFT_AIMED_SHOT_IMPACT);
      local1.push(SHAFT_ROTATION_DECELERATION_COEFF);
      local1.push(SHAFT_FAST_SHOT_ENERGY);
      local1.push(SHAFT_MIN_AIMED_SHOT_ENERGY);
      local1.push(WEAPON_CHARGE_RATE);
      local1.push(WEAPON_KICKBACK);
      local1.push(WEAPON_MIN_DAMAGE_PERCENT);
      local1.push(WEAPON_MIN_DAMAGE_RADIUS);
      local1.push(WEAPON_MAX_DAMAGE_RADIUS);
      local1.push(SHOT_RANGE);
      local1.push(MAX_CRITICAL_HIT_CHANCE);
      local1.push(START_CRITICAL_HIT_CHANCE);
      local1.push(AFTER_CRIT_CRITICAL_HIT_CHANCE);
      local1.push(CRITICAL_CHANCE_DELTA);
      local1.push(CRITICAL_HIT_CHANCE);
      local1.push(CRITICAL_HIT_DAMAGE);
      local1.push(SPLASH_DAMAGE_RADIUS);
      local1.push(RADIUS_OF_MAX_SPLASH_DAMAGE);
      local1.push(MIN_SPLASH_DAMAGE_PERCENT);
      local1.push(SPLASH_DAMAGE_IMPACT);
      local1.push(RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE);
      local1.push(FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT);
      local1.push(WEAPON_DISCHARGE_RATE);
      local1.push(DAMAGE_PER_PERIOD);
      local1.push(ISIS_HEALING_PER_PERIOD);
      local1.push(ISIS_INCREASE_TARGET_TEMPERATURE_PER_TICK);
      local1.push(ISIS_DECREASE_TARGET_TEMPERATURE_PER_TICK);
      local1.push(ISIS_DISCHARGE_SPEED_HEALING);
      local1.push(ISIS_DISCHARGE_SPEED_IDLE);
      local1.push(FLAME_TEMPERATURE_LIMIT);
      local1.push(HEAT_PER_PERIOD);
      local1.push(ENERGY_PER_SHOT);
      local1.push(MACHINE_GUN_SELF_TEMPERATURE_INCREASE_PER_SECOND);
      local1.push(MACHINE_GUN_SPIN_UP_TIME_SECOND);
      local1.push(MACHINE_GUN_SPIN_DOWN_TIME_SECOND);
      local1.push(MACHINE_GUN_WEAPON_TURN_DECELERATION_COEFF);
      local1.push(MACHINE_GUN_TEMPERATURE_HITTING_TIME_SECOND);
      local1.push(MACHINE_GUN_OVERHEAT_DAMAGE_COEFF);
      local1.push(MACHINE_GUN_POWER_WHEN_TANK_TEMPERATURE_START_INCREASE);
      local1.push(ELLIPTIC_CONE_VERTICAL_ANGLE);
      local1.push(ELLIPTIC_CONE_HORIZONTAL_ANGLE);
      local1.push(SHOTGUN_MAGAZINE_SIZE);
      local1.push(SHOTGUN_PELLET_COUNT);
      local1.push(MAGAZINE_RELOAD_TIME);
      local1.push(DAMAGE_PER_HIT);
      local1.push(DISCHARGE_SPEED);
      local1.push(CONE_ANGLE);
      local1.push(FREEZE_PER_TICK);
      local1.push(WEAPON_ANGLE_UP);
      local1.push(WEAPON_ANGLE_DOWN);
      local1.push(ROCKET_ANGULAR_VELOCITY);
      local1.push(SALVO_AIMING_TIME);
      local1.push(SALVO_AIMING_GRACE_PERIOD);
      local1.push(TIME_BETWEEN_SHOTS_OF_SALVO);
      local1.push(SALVO_RELOAD_TIME);
      local1.push(SALVO_SIZE);
      local1.push(SHELL_SPEED);
      local1.push(SHELL_RADIUS);
      local1.push(MIN_SHELL_SPEED);
      local1.push(MAX_SHELL_SPEED);
      local1.push(SHELL_BOOST_PHASE_DURATION);
      local1.push(SHELL_SPEEDS_COUNT);
      local1.push(SHELL_GRAVITY_COEF);
      local1.push(MAX_RICOCHET_COUNT);
      local1.push(SECONDARY_WEAPON_KICKBACK);
      local1.push(SECONDARY_DAMAGE_FROM);
      local1.push(SECONDARY_DAMAGE_TO);
      local1.push(HIGHLIGHTING_DISTANCE);
      local1.push(DRONE_RELOAD);
      local1.push(DRONE_REPAIR_HEALTH);
      local1.push(DRONE_REPAIR_RADIUS);
      local1.push(DRONE_INVENTORY);
      local1.push(DRONE_INVENTORY_ADD);
      local1.push(DRONE_BONUS_ADD);
      local1.push(DRONE_FIRST_AID_BONUS_ADD);
      local1.push(DRONE_OVERDRIVE_BOOST);
      local1.push(DRONE_INVENTORY_RADIUS);
      local1.push(DRONE_COOLDOWN_RADIUS);
      local1.push(DRONE_DEFEND);
      local1.push(DRONE_ARMOR_BOOST);
      local1.push(DRONE_MINE);
      local1.push(DRONE_ADDITIONAL_MINES);
      local1.push(DRONE_MINES_ACTIVATION_DELAY);
      local1.push(DRONE_INVENTORY_COOLDOWN_BOOST);
      local1.push(DRONE_MINES_PLACEMENT_RADIUS);
      local1.push(DRONE_POWER_BOOST);
      local1.push(DRONE_POWER_DURATION);
      local1.push(DRONE_CRITICAL_HEALTH);
      local1.push(DRONE_CONSTANT_ARMOR_PERCENT);
      local1.push(DRONE_CONSTANT_POWER_PERCENT);
      local1.push(ULTIMATE_HEAL_HP);
      local1.push(DEVICE_TEMPERATURE_NORMALIZATION);
      local1.push(DEVICE_BONUS_ENERGY_ON_KILL);
      local1.push(DEVICE_HEAT_PER_PELLET);
      local1.push(DEVICE_SMOKY_TEMPERATURE_DELTA_ON_CRITICAL);
      local1.push(DEVICE_TARGET_HEAT_DELTA_ON_SELF_OVERHEAT);
      local1.push(ULTIMATE_CHARGE_PER_SEC);
      local1.push(ULTIMATE_CHARGE_PER_SCORE_POINT);
      local1.push(ULTIMATE_SCORE_COOLDOWN_SEC);
      local1.push(ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC);
      local1.push(GAUSS_AIMED_SHOT_IMPACT);
      local1.push(GAUSS_AIMED_SPLASH_DAMAGE_RADIUS);
      local1.push(GAUSS_AIMED_RADIUS_OF_MAX_SPLASH_DAMAGE);
      local1.push(GAUSS_AIMED_MIN_SPLASH_DAMAGE_PERCENT);
      local1.push(GAUSS_AIMED_SPLASH_DAMAGE_IMPACT);
      local1.push(GAUSS_AIMED_RADIUS_OF_FIRST_DIMINUTION_SPLASH_DAMAGE);
      local1.push(GAUSS_AIMED_FIRST_DIMINUTION_SPLASH_DAMAGE_PERCENT);
      return local1;
    }

    public function toString() : String {
      return "ItemProperty [" + this._name + "]";
    }

    public function get value() : int {
      return this._value;
    }

    public function get name() : String {
      return this._name;
    }
  }
}
