package projects.tanks.client.commons.osgi {
  import _codec.map.String__String;
  import _codec.projects.tanks.client.commons.models.captcha.CodecCaptchaCC;
  import _codec.projects.tanks.client.commons.models.captcha.CodecCaptchaLocation;
  import _codec.projects.tanks.client.commons.models.captcha.VectorCodecCaptchaCCLevel1;
  import _codec.projects.tanks.client.commons.models.captcha.VectorCodecCaptchaLocationLevel1;
  import _codec.projects.tanks.client.commons.models.challenge.time.CodecChallengesTimeCC;
  import _codec.projects.tanks.client.commons.models.challenge.time.VectorCodecChallengesTimeCCLevel1;
  import _codec.projects.tanks.client.commons.models.coloring.CodecColoringCC;
  import _codec.projects.tanks.client.commons.models.coloring.VectorCodecColoringCCLevel1;
  import _codec.projects.tanks.client.commons.models.externalauth.CodecExternalAuthParameters;
  import _codec.projects.tanks.client.commons.models.externalauth.VectorCodecExternalAuthParametersLevel1;
  import _codec.projects.tanks.client.commons.models.layout.CodecLayoutState;
  import _codec.projects.tanks.client.commons.models.layout.VectorCodecLayoutStateLevel1;
  import _codec.projects.tanks.client.commons.models.runtime.CodecDataOwnerCC;
  import _codec.projects.tanks.client.commons.models.runtime.VectorCodecDataOwnerCCLevel1;
  import _codec.projects.tanks.client.commons.socialnetwork.CodecSocialNetworkEnum;
  import _codec.projects.tanks.client.commons.socialnetwork.VectorCodecSocialNetworkEnumLevel1;
  import _codec.projects.tanks.client.commons.types.CodecItemCategoryEnum;
  import _codec.projects.tanks.client.commons.types.CodecItemGarageProperty;
  import _codec.projects.tanks.client.commons.types.CodecItemViewCategoryEnum;
  import _codec.projects.tanks.client.commons.types.CodecShopAbonementBonusTypeEnum;
  import _codec.projects.tanks.client.commons.types.CodecShopCategoryEnum;
  import _codec.projects.tanks.client.commons.types.VectorCodecItemCategoryEnumLevel1;
  import _codec.projects.tanks.client.commons.types.VectorCodecItemGaragePropertyLevel1;
  import _codec.projects.tanks.client.commons.types.VectorCodecItemViewCategoryEnumLevel1;
  import _codec.projects.tanks.client.commons.types.VectorCodecShopAbonementBonusTypeEnumLevel1;
  import _codec.projects.tanks.client.commons.types.VectorCodecShopCategoryEnumLevel1;
  import alternativa.osgi.OSGi;
  import alternativa.osgi.bundle.IBundleActivator;
  import alternativa.protocol.ICodec;
  import alternativa.protocol.IProtocol;
  import alternativa.protocol.codec.OptionalCodecDecorator;
  import alternativa.protocol.info.CollectionCodecInfo;
  import alternativa.protocol.info.EnumCodecInfo;
  import alternativa.protocol.info.MapCodecInfo;
  import alternativa.protocol.info.TypeCodecInfo;
  import alternativa.types.Long;
  import platform.client.fp10.core.registry.ModelRegistry;
  import projects.tanks.client.commons.models.captcha.CaptchaCC;
  import projects.tanks.client.commons.models.captcha.CaptchaLocation;
  import projects.tanks.client.commons.models.challenge.time.ChallengesTimeCC;
  import projects.tanks.client.commons.models.coloring.ColoringCC;
  import projects.tanks.client.commons.models.externalauth.ExternalAuthParameters;
  import projects.tanks.client.commons.models.layout.LayoutState;
  import projects.tanks.client.commons.models.runtime.DataOwnerCC;
  import projects.tanks.client.commons.socialnetwork.SocialNetworkEnum;
  import projects.tanks.client.commons.types.ItemCategoryEnum;
  import projects.tanks.client.commons.types.ItemGarageProperty;
  import projects.tanks.client.commons.types.ItemViewCategoryEnum;
  import projects.tanks.client.commons.types.ShopAbonementBonusTypeEnum;
  import projects.tanks.client.commons.types.ShopCategoryEnum;

  public class Activator implements IBundleActivator {
    public static var osgi:OSGi;

    public function Activator() {
      super();
    }

    public function start(param1:OSGi) : void {
      var local4:ICodec = null;
      osgi = param1;
      var local2:ModelRegistry = ModelRegistry(OSGi.getInstance().getService(ModelRegistry));
      local2.register(Long.getLong(2058573415,-746879275),Long.getLong(888592950,-646476035));
      local2.register(Long.getLong(490831193,1530810385),Long.getLong(1163794707,1156292692));
      local2.register(Long.getLong(490831193,1530810385),Long.getLong(176089096,-444205293));
      local2.register(Long.getLong(490831193,1530810385),Long.getLong(1404540170,-251744121));
      local2.register(Long.getLong(1481647778,-291699533),Long.getLong(1809738995,677658011));
      local2.register(Long.getLong(1481647778,-291699533),Long.getLong(527428095,-1647091354));
      local2.register(Long.getLong(1481647778,-291699533),Long.getLong(2122248367,-1459259159));
      local2.register(Long.getLong(650947056,1487530419),Long.getLong(14163504,1184321813));
      local2.register(Long.getLong(650947056,1487530419),Long.getLong(2016074577,529714967));
      local2.register(Long.getLong(650947056,1487530419),Long.getLong(969374437,-1423594874));
      local2.register(Long.getLong(1594319086,-307533593),Long.getLong(1584343746,-1931074163));
      local2.register(Long.getLong(1670604947,523994521),Long.getLong(617627221,751287008));
      var local3:IProtocol = IProtocol(osgi.getService(IProtocol));
      local4 = new CodecCaptchaCC();
      local3.registerCodec(new TypeCodecInfo(CaptchaCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(CaptchaCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecCaptchaLocation();
      local3.registerCodec(new EnumCodecInfo(CaptchaLocation,false),local4);
      local3.registerCodec(new EnumCodecInfo(CaptchaLocation,true),new OptionalCodecDecorator(local4));
      local4 = new CodecChallengesTimeCC();
      local3.registerCodec(new TypeCodecInfo(ChallengesTimeCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ChallengesTimeCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecColoringCC();
      local3.registerCodec(new TypeCodecInfo(ColoringCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(ColoringCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecExternalAuthParameters();
      local3.registerCodec(new TypeCodecInfo(ExternalAuthParameters,false),local4);
      local3.registerCodec(new TypeCodecInfo(ExternalAuthParameters,true),new OptionalCodecDecorator(local4));
      local4 = new CodecLayoutState();
      local3.registerCodec(new EnumCodecInfo(LayoutState,false),local4);
      local3.registerCodec(new EnumCodecInfo(LayoutState,true),new OptionalCodecDecorator(local4));
      local4 = new CodecDataOwnerCC();
      local3.registerCodec(new TypeCodecInfo(DataOwnerCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(DataOwnerCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecSocialNetworkEnum();
      local3.registerCodec(new EnumCodecInfo(SocialNetworkEnum,false),local4);
      local3.registerCodec(new EnumCodecInfo(SocialNetworkEnum,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemCategoryEnum();
      local3.registerCodec(new EnumCodecInfo(ItemCategoryEnum,false),local4);
      local3.registerCodec(new EnumCodecInfo(ItemCategoryEnum,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemGarageProperty();
      local3.registerCodec(new EnumCodecInfo(ItemGarageProperty,false),local4);
      local3.registerCodec(new EnumCodecInfo(ItemGarageProperty,true),new OptionalCodecDecorator(local4));
      local4 = new CodecItemViewCategoryEnum();
      local3.registerCodec(new EnumCodecInfo(ItemViewCategoryEnum,false),local4);
      local3.registerCodec(new EnumCodecInfo(ItemViewCategoryEnum,true),new OptionalCodecDecorator(local4));
      local4 = new CodecShopAbonementBonusTypeEnum();
      local3.registerCodec(new EnumCodecInfo(ShopAbonementBonusTypeEnum,false),local4);
      local3.registerCodec(new EnumCodecInfo(ShopAbonementBonusTypeEnum,true),new OptionalCodecDecorator(local4));
      local4 = new CodecShopCategoryEnum();
      local3.registerCodec(new EnumCodecInfo(ShopCategoryEnum,false),local4);
      local3.registerCodec(new EnumCodecInfo(ShopCategoryEnum,true),new OptionalCodecDecorator(local4));
      local4 = new String__String(false,false);
      local3.registerCodec(new MapCodecInfo(new TypeCodecInfo(String,false),new TypeCodecInfo(String,false),false),local4);
      local3.registerCodec(new MapCodecInfo(new TypeCodecInfo(String,false),new TypeCodecInfo(String,false),true),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCaptchaCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CaptchaCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CaptchaCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCaptchaCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CaptchaCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(CaptchaCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCaptchaLocationLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(CaptchaLocation,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(CaptchaLocation,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecCaptchaLocationLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(CaptchaLocation,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(CaptchaLocation,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecChallengesTimeCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ChallengesTimeCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ChallengesTimeCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecChallengesTimeCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ChallengesTimeCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ChallengesTimeCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecColoringCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ColoringCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ColoringCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecColoringCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ColoringCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ColoringCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecExternalAuthParametersLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ExternalAuthParameters,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ExternalAuthParameters,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecExternalAuthParametersLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ExternalAuthParameters,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(ExternalAuthParameters,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecLayoutStateLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(LayoutState,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(LayoutState,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecLayoutStateLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(LayoutState,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(LayoutState,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDataOwnerCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DataOwnerCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DataOwnerCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecDataOwnerCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DataOwnerCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(DataOwnerCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecSocialNetworkEnumLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(SocialNetworkEnum,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(SocialNetworkEnum,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecSocialNetworkEnumLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(SocialNetworkEnum,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(SocialNetworkEnum,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemCategoryEnumLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemCategoryEnum,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemCategoryEnum,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemCategoryEnumLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemCategoryEnum,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemCategoryEnum,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemGaragePropertyLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemGarageProperty,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemGarageProperty,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemGaragePropertyLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemGarageProperty,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemGarageProperty,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemViewCategoryEnumLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemViewCategoryEnum,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemViewCategoryEnum,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecItemViewCategoryEnumLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemViewCategoryEnum,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ItemViewCategoryEnum,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopAbonementBonusTypeEnumLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopAbonementBonusTypeEnum,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopAbonementBonusTypeEnum,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopAbonementBonusTypeEnumLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopAbonementBonusTypeEnum,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopAbonementBonusTypeEnum,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopCategoryEnumLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopCategoryEnum,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopCategoryEnum,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecShopCategoryEnumLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopCategoryEnum,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(ShopCategoryEnum,true),true,1),new OptionalCodecDecorator(local4));
    }

    public function stop(param1:OSGi) : void {
    }
  }
}
