package projects.tanks.client.battleservice.osgi {
  import _codec.projects.tanks.client.battleservice.CodecBattleCreateParameters;
  import _codec.projects.tanks.client.battleservice.CodecBattleMode;
  import _codec.projects.tanks.client.battleservice.CodecBattleRoundParameters;
  import _codec.projects.tanks.client.battleservice.CodecRange;
  import _codec.projects.tanks.client.battleservice.VectorCodecBattleCreateParametersLevel1;
  import _codec.projects.tanks.client.battleservice.VectorCodecBattleModeLevel1;
  import _codec.projects.tanks.client.battleservice.VectorCodecBattleRoundParametersLevel1;
  import _codec.projects.tanks.client.battleservice.VectorCodecRangeLevel1;
  import _codec.projects.tanks.client.battleservice.model.battle.team.CodecBattleTeam;
  import _codec.projects.tanks.client.battleservice.model.battle.team.VectorCodecBattleTeamLevel1;
  import _codec.projects.tanks.client.battleservice.model.createparams.CodecBattleLimits;
  import _codec.projects.tanks.client.battleservice.model.createparams.VectorCodecBattleLimitsLevel1;
  import _codec.projects.tanks.client.battleservice.model.map.params.CodecMapTheme;
  import _codec.projects.tanks.client.battleservice.model.map.params.VectorCodecMapThemeLevel1;
  import _codec.projects.tanks.client.battleservice.model.performance.CodecPerformanceCC;
  import _codec.projects.tanks.client.battleservice.model.performance.VectorCodecPerformanceCCLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.CodecStatisticsModelCC;
  import _codec.projects.tanks.client.battleservice.model.statistics.CodecUserInfo;
  import _codec.projects.tanks.client.battleservice.model.statistics.CodecUserReward;
  import _codec.projects.tanks.client.battleservice.model.statistics.CodecUserStat;
  import _codec.projects.tanks.client.battleservice.model.statistics.VectorCodecStatisticsModelCCLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.VectorCodecUserInfoLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.VectorCodecUserRewardLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.VectorCodecUserStatLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.dm.CodecStatisticsDMCC;
  import _codec.projects.tanks.client.battleservice.model.statistics.dm.VectorCodecStatisticsDMCCLevel1;
  import _codec.projects.tanks.client.battleservice.model.statistics.team.CodecStatisticsTeamCC;
  import _codec.projects.tanks.client.battleservice.model.statistics.team.VectorCodecStatisticsTeamCCLevel1;
  import _codec.projects.tanks.client.battleservice.model.types.CodecBattleSuspicionLevel;
  import _codec.projects.tanks.client.battleservice.model.types.VectorCodecBattleSuspicionLevelLevel1;
  import alternativa.osgi.OSGi;
  import alternativa.osgi.bundle.IBundleActivator;
  import alternativa.protocol.ICodec;
  import alternativa.protocol.IProtocol;
  import alternativa.protocol.codec.OptionalCodecDecorator;
  import alternativa.protocol.info.CollectionCodecInfo;
  import alternativa.protocol.info.EnumCodecInfo;
  import alternativa.protocol.info.TypeCodecInfo;
  import alternativa.types.Long;
  import platform.client.fp10.core.registry.ModelRegistry;
  import projects.tanks.client.battleservice.BattleCreateParameters;
  import projects.tanks.client.battleservice.BattleMode;
  import projects.tanks.client.battleservice.BattleRoundParameters;
  import projects.tanks.client.battleservice.Range;
  import projects.tanks.client.battleservice.model.battle.team.BattleTeam;
  import projects.tanks.client.battleservice.model.createparams.BattleLimits;
  import projects.tanks.client.battleservice.model.map.params.MapTheme;
  import projects.tanks.client.battleservice.model.performance.PerformanceCC;
  import projects.tanks.client.battleservice.model.statistics.StatisticsModelCC;
  import projects.tanks.client.battleservice.model.statistics.UserInfo;
  import projects.tanks.client.battleservice.model.statistics.UserReward;
  import projects.tanks.client.battleservice.model.statistics.UserStat;
  import projects.tanks.client.battleservice.model.statistics.dm.StatisticsDMCC;
  import projects.tanks.client.battleservice.model.statistics.team.StatisticsTeamCC;
  import projects.tanks.client.battleservice.model.types.BattleSuspicionLevel;

  public class Activator implements IBundleActivator {
    public static var osgi:OSGi;

    public function Activator() {
      super();
    }

    public function start(param1:OSGi) : void {
      var local4:ICodec = null;
      osgi = param1;
      var local2:ModelRegistry = ModelRegistry(OSGi.getInstance().getService(ModelRegistry));
      local2.register(Long.getLong(121770418,618912707),Long.getLong(335434599,-27161610));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(2027633487,-2104416877));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(794588440,-1349024015));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(1688328639,-1477155462));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(1570125867,640719657));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(2027560760,1768125684));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(1312331174,-81511448));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(1481208751,-1671478579));
      local2.register(Long.getLong(485575169,-17734339),Long.getLong(844922966,157499169));
      local2.register(Long.getLong(575618390,177970779),Long.getLong(965223943,535616065));
      local2.register(Long.getLong(575618390,177970779),Long.getLong(2010192701,-2134483217));
      local2.register(Long.getLong(575618390,177970779),Long.getLong(825794462,-1556026223));
      local2.register(Long.getLong(575618390,177970779),Long.getLong(329840042,1301345271));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(1367071399,-1702461867));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(1479921566,-1347191967));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(1581597391,-963196943));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(1345957775,1774893408));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(386945968,-373481329));
      local2.register(Long.getLong(183455729,-2099733819),Long.getLong(184857581,1110813993));
      var local3:IProtocol = IProtocol(osgi.getService(IProtocol));
      local4 = new CodecBattleCreateParameters();
      local3.registerCodec(new TypeCodecInfo(BattleCreateParameters,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleCreateParameters,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleMode();
      local3.registerCodec(new EnumCodecInfo(BattleMode,false),local4);
      local3.registerCodec(new EnumCodecInfo(BattleMode,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleRoundParameters();
      local3.registerCodec(new TypeCodecInfo(BattleRoundParameters,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleRoundParameters,true),new OptionalCodecDecorator(local4));
      local4 = new CodecRange();
      local3.registerCodec(new TypeCodecInfo(Range,false),local4);
      local3.registerCodec(new TypeCodecInfo(Range,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleTeam();
      local3.registerCodec(new EnumCodecInfo(BattleTeam,false),local4);
      local3.registerCodec(new EnumCodecInfo(BattleTeam,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleLimits();
      local3.registerCodec(new TypeCodecInfo(BattleLimits,false),local4);
      local3.registerCodec(new TypeCodecInfo(BattleLimits,true),new OptionalCodecDecorator(local4));
      local4 = new CodecMapTheme();
      local3.registerCodec(new EnumCodecInfo(MapTheme,false),local4);
      local3.registerCodec(new EnumCodecInfo(MapTheme,true),new OptionalCodecDecorator(local4));
      local4 = new CodecPerformanceCC();
      local3.registerCodec(new TypeCodecInfo(PerformanceCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(PerformanceCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecStatisticsModelCC();
      local3.registerCodec(new TypeCodecInfo(StatisticsModelCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(StatisticsModelCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUserInfo();
      local3.registerCodec(new TypeCodecInfo(UserInfo,false),local4);
      local3.registerCodec(new TypeCodecInfo(UserInfo,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUserReward();
      local3.registerCodec(new TypeCodecInfo(UserReward,false),local4);
      local3.registerCodec(new TypeCodecInfo(UserReward,true),new OptionalCodecDecorator(local4));
      local4 = new CodecUserStat();
      local3.registerCodec(new TypeCodecInfo(UserStat,false),local4);
      local3.registerCodec(new TypeCodecInfo(UserStat,true),new OptionalCodecDecorator(local4));
      local4 = new CodecStatisticsDMCC();
      local3.registerCodec(new TypeCodecInfo(StatisticsDMCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(StatisticsDMCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecStatisticsTeamCC();
      local3.registerCodec(new TypeCodecInfo(StatisticsTeamCC,false),local4);
      local3.registerCodec(new TypeCodecInfo(StatisticsTeamCC,true),new OptionalCodecDecorator(local4));
      local4 = new CodecBattleSuspicionLevel();
      local3.registerCodec(new EnumCodecInfo(BattleSuspicionLevel,false),local4);
      local3.registerCodec(new EnumCodecInfo(BattleSuspicionLevel,true),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleCreateParametersLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateParameters,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateParameters,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleCreateParametersLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateParameters,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleCreateParameters,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleModeLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleMode,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleMode,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleModeLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleMode,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleMode,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleRoundParametersLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleRoundParameters,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleRoundParameters,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleRoundParametersLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleRoundParameters,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleRoundParameters,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRangeLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Range,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Range,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecRangeLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Range,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(Range,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleTeamLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleTeam,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleTeam,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleTeamLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleTeam,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleTeam,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleLimitsLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleLimits,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleLimits,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleLimitsLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleLimits,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(BattleLimits,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMapThemeLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MapTheme,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MapTheme,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecMapThemeLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MapTheme,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(MapTheme,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPerformanceCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PerformanceCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PerformanceCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecPerformanceCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PerformanceCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(PerformanceCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsModelCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsModelCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsModelCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsModelCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsModelCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsModelCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserInfoLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserInfo,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserInfo,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserInfoLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserInfo,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserInfo,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserRewardLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserReward,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserReward,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserRewardLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserReward,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserReward,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserStatLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserStat,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserStat,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecUserStatLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserStat,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(UserStat,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsDMCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsDMCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsDMCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsDMCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsDMCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsDMCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsTeamCCLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsTeamCC,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsTeamCC,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecStatisticsTeamCCLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsTeamCC,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new TypeCodecInfo(StatisticsTeamCC,true),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleSuspicionLevelLevel1(false);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSuspicionLevel,false),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSuspicionLevel,false),true,1),new OptionalCodecDecorator(local4));
      local4 = new VectorCodecBattleSuspicionLevelLevel1(true);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSuspicionLevel,true),false,1),local4);
      local3.registerCodec(new CollectionCodecInfo(new EnumCodecInfo(BattleSuspicionLevel,true),true,1),new OptionalCodecDecorator(local4));
    }

    public function stop(param1:OSGi) : void {
    }
  }
}
