package projects.tanks.client.commons.types {
  public class ItemGarageProperty {
    public static const HULL_ARMOR:ItemGarageProperty = new ItemGarageProperty(0,"HULL_ARMOR");
    public static const HULL_SPEED:ItemGarageProperty = new ItemGarageProperty(1,"HULL_SPEED");
    public static const HULL_TURN_SPEED:ItemGarageProperty = new ItemGarageProperty(2,"HULL_TURN_SPEED");
    public static const HULL_POWER:ItemGarageProperty = new ItemGarageProperty(3,"HULL_POWER");
    public static const HULL_MASS:ItemGarageProperty = new ItemGarageProperty(4,"HULL_MASS");
    public static const ALL_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(5,"ALL_RESISTANCE");
    public static const FIREBIRD_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(6,"FIREBIRD_RESISTANCE");
    public static const SMOKY_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(7,"SMOKY_RESISTANCE");
    public static const TWINS_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(8,"TWINS_RESISTANCE");
    public static const RAILGUN_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(9,"RAILGUN_RESISTANCE");
    public static const ISIS_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(10,"ISIS_RESISTANCE");
    public static const MINE_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(11,"MINE_RESISTANCE");
    public static const THUNDER_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(12,"THUNDER_RESISTANCE");
    public static const FREEZE_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(13,"FREEZE_RESISTANCE");
    public static const RICOCHET_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(14,"RICOCHET_RESISTANCE");
    public static const SHAFT_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(15,"SHAFT_RESISTANCE");
    public static const SHOTGUN_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(16,"SHOTGUN_RESISTANCE");
    public static const MACHINE_GUN_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(17,"MACHINE_GUN_RESISTANCE");
    public static const ROCKET_LAUNCHER_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(18,"ROCKET_LAUNCHER_RESISTANCE");
    public static const ARTILLERY_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(19,"ARTILLERY_RESISTANCE");
    public static const GAUSS_RESISTANCE:ItemGarageProperty = new ItemGarageProperty(20,"GAUSS_RESISTANCE");
    public static const DAMAGE:ItemGarageProperty = new ItemGarageProperty(21,"DAMAGE");
    public static const DAMAGE_PER_SECOND:ItemGarageProperty = new ItemGarageProperty(22,"DAMAGE_PER_SECOND");
    public static const WEAPON_COOLDOWN_TIME:ItemGarageProperty = new ItemGarageProperty(23,"WEAPON_COOLDOWN_TIME");
    public static const AIMING_MODE_COOLDOWN_TIME:ItemGarageProperty = new ItemGarageProperty(24,"AIMING_MODE_COOLDOWN_TIME");
    public static const CRITICAL_HIT_CHANCE:ItemGarageProperty = new ItemGarageProperty(25,"CRITICAL_HIT_CHANCE");
    public static const CRITICAL_HIT_DAMAGE:ItemGarageProperty = new ItemGarageProperty(26,"CRITICAL_HIT_DAMAGE");
    public static const SHOT_RANGE:ItemGarageProperty = new ItemGarageProperty(27,"SHOT_RANGE");
    public static const TURRET_TURN_SPEED:ItemGarageProperty = new ItemGarageProperty(28,"TURRET_TURN_SPEED");
    public static const AIMING_ERROR:ItemGarageProperty = new ItemGarageProperty(29,"AIMING_ERROR");
    public static const SHOT_AREA:ItemGarageProperty = new ItemGarageProperty(30,"SHOT_AREA");
    public static const CONE_ANGLE:ItemGarageProperty = new ItemGarageProperty(31,"CONE_ANGLE");
    public static const CHARGING_TIME:ItemGarageProperty = new ItemGarageProperty(32,"CHARGING_TIME");
    public static const FIRE_DAMAGE:ItemGarageProperty = new ItemGarageProperty(33,"FIRE_DAMAGE");
    public static const WEAPON_WEAKENING_COEFF:ItemGarageProperty = new ItemGarageProperty(34,"WEAPON_WEAKENING_COEFF");
    public static const ISIS_DAMAGE:ItemGarageProperty = new ItemGarageProperty(35,"ISIS_DAMAGE");
    public static const ISIS_HEALING_PER_SECOND:ItemGarageProperty = new ItemGarageProperty(36,"ISIS_HEALING_PER_SECOND");
    public static const AIMING_MODE_DAMAGE:ItemGarageProperty = new ItemGarageProperty(37,"AIMING_MODE_DAMAGE");
    public static const AIMING_WEAPON_DISCHARGE_RATE:ItemGarageProperty = new ItemGarageProperty(38,"AIMING_WEAPON_DISCHARGE_RATE");
    public static const SHAFT_AIMED_SHOT_IMPACT:ItemGarageProperty = new ItemGarageProperty(39,"SHAFT_AIMED_SHOT_IMPACT");
    public static const SHAFT_TARGETING_SPEED:ItemGarageProperty = new ItemGarageProperty(40,"SHAFT_TARGETING_SPEED");
    public static const SHAFT_ARCADE_DAMAGE:ItemGarageProperty = new ItemGarageProperty(41,"SHAFT_ARCADE_DAMAGE");
    public static const GAUSS_AIMING_MODE_DAMAGE:ItemGarageProperty = new ItemGarageProperty(42,"GAUSS_AIMING_MODE_DAMAGE");
    public static const WEAPON_IMPACT_FORCE:ItemGarageProperty = new ItemGarageProperty(43,"WEAPON_IMPACT_FORCE");
    public static const WEAPON_KICKBACK:ItemGarageProperty = new ItemGarageProperty(44,"WEAPON_KICKBACK");
    public static const SHELL_SPEED:ItemGarageProperty = new ItemGarageProperty(45,"SHELL_SPEED");
    public static const WEAPON_CHARGE_RATE:ItemGarageProperty = new ItemGarageProperty(46,"WEAPON_CHARGE_RATE");
    public static const WEAPON_MIN_DAMAGE_PERCENT:ItemGarageProperty = new ItemGarageProperty(47,"WEAPON_MIN_DAMAGE_PERCENT");
    public static const THUNDER_MIN_SPLASH_DAMAGE_PERCENT:ItemGarageProperty = new ItemGarageProperty(48,"THUNDER_MIN_SPLASH_DAMAGE_PERCENT");
    public static const DEPENDENCY_FIRST_AID_SEC:ItemGarageProperty = new ItemGarageProperty(49,"DEPENDENCY_FIRST_AID_SEC");
    public static const DEPENDENCY_DOUBLE_ARMOR_SEC:ItemGarageProperty = new ItemGarageProperty(50,"DEPENDENCY_DOUBLE_ARMOR_SEC");
    public static const DEPENDENCY_DOUBLE_DAMAGE_SEC:ItemGarageProperty = new ItemGarageProperty(51,"DEPENDENCY_DOUBLE_DAMAGE_SEC");
    public static const DEPENDENCY_NITRO_SEC:ItemGarageProperty = new ItemGarageProperty(52,"DEPENDENCY_NITRO_SEC");
    public static const DEPENDENCY_MINE_SEC:ItemGarageProperty = new ItemGarageProperty(53,"DEPENDENCY_MINE_SEC");
    public static const DEPENDENCY_DROPPABLE_GOLD_SEC:ItemGarageProperty = new ItemGarageProperty(54,"DEPENDENCY_DROPPABLE_GOLD_SEC");
    public static const COOLDOWN_FIRST_AID_SEC:ItemGarageProperty = new ItemGarageProperty(55,"COOLDOWN_FIRST_AID_SEC");
    public static const COOLDOWN_DOUBLE_ARMOR_SEC:ItemGarageProperty = new ItemGarageProperty(56,"COOLDOWN_DOUBLE_ARMOR_SEC");
    public static const COOLDOWN_DOUBLE_DAMAGE_SEC:ItemGarageProperty = new ItemGarageProperty(57,"COOLDOWN_DOUBLE_DAMAGE_SEC");
    public static const COOLDOWN_NITRO_SEC:ItemGarageProperty = new ItemGarageProperty(58,"COOLDOWN_NITRO_SEC");
    public static const COOLDOWN_MINE_SEC:ItemGarageProperty = new ItemGarageProperty(59,"COOLDOWN_MINE_SEC");
    public static const COOLDOWN_DROPPABLE_GOLD_SEC:ItemGarageProperty = new ItemGarageProperty(60,"COOLDOWN_DROPPABLE_GOLD_SEC");
    public static const DURATION_FIRST_AID_SEC:ItemGarageProperty = new ItemGarageProperty(61,"DURATION_FIRST_AID_SEC");
    public static const DURATION_DOUBLE_ARMOR_SEC:ItemGarageProperty = new ItemGarageProperty(62,"DURATION_DOUBLE_ARMOR_SEC");
    public static const DURATION_DOUBLE_DAMAGE_SEC:ItemGarageProperty = new ItemGarageProperty(63,"DURATION_DOUBLE_DAMAGE_SEC");
    public static const DURATION_NITRO_SEC:ItemGarageProperty = new ItemGarageProperty(64,"DURATION_NITRO_SEC");
    public static const ATTACK_EFFECT:ItemGarageProperty = new ItemGarageProperty(65,"ATTACK_EFFECT");
    public static const FIRST_AID_EFFECT_INSTANT:ItemGarageProperty = new ItemGarageProperty(66,"FIRST_AID_EFFECT_INSTANT");
    public static const FIRST_AID_EFFECT:ItemGarageProperty = new ItemGarageProperty(67,"FIRST_AID_EFFECT");
    public static const PROTECTION_EFFECT:ItemGarageProperty = new ItemGarageProperty(68,"PROTECTION_EFFECT");
    public static const SPEED_EFFECT:ItemGarageProperty = new ItemGarageProperty(69,"SPEED_EFFECT");
    public static const SHOTGUN_IMPACT_FORCE:ItemGarageProperty = new ItemGarageProperty(70,"SHOTGUN_IMPACT_FORCE");
    public static const DISCHARGE_SPEED:ItemGarageProperty = new ItemGarageProperty(71,"DISCHARGE_SPEED");
    public static const FREEZE_PER_TICK:ItemGarageProperty = new ItemGarageProperty(72,"FREEZE_PER_TICK");
    public static const VERTICAL_ANGLES:ItemGarageProperty = new ItemGarageProperty(73,"VERTICAL_ANGLES");
    public static const DRONE_RELOAD:ItemGarageProperty = new ItemGarageProperty(74,"DRONE_RELOAD");
    public static const DRONE_REPAIR_HEALTH:ItemGarageProperty = new ItemGarageProperty(75,"DRONE_REPAIR_HEALTH");
    public static const DRONE_INVENTORY:ItemGarageProperty = new ItemGarageProperty(76,"DRONE_INVENTORY");
    public static const DRONE_INVENTORY_ADD:ItemGarageProperty = new ItemGarageProperty(77,"DRONE_INVENTORY_ADD");
    public static const DRONE_BONUS_ADD:ItemGarageProperty = new ItemGarageProperty(78,"DRONE_BONUS_ADD");
    public static const DRONE_FIRST_AID_BONUS_ADD:ItemGarageProperty = new ItemGarageProperty(79,"DRONE_FIRST_AID_BONUS_ADD");
    public static const DRONE_OVERDRIVE_BOOST:ItemGarageProperty = new ItemGarageProperty(80,"DRONE_OVERDRIVE_BOOST");
    public static const DRONE_DEFEND:ItemGarageProperty = new ItemGarageProperty(81,"DRONE_DEFEND");
    public static const DRONE_ARMOR_BOOST:ItemGarageProperty = new ItemGarageProperty(82,"DRONE_ARMOR_BOOST");
    public static const DRONE_MINE:ItemGarageProperty = new ItemGarageProperty(83,"DRONE_MINE");
    public static const DRONE_ADDITIONAL_MINES:ItemGarageProperty = new ItemGarageProperty(84,"DRONE_ADDITIONAL_MINES");
    public static const DRONE_MINES_ACTIVATION_DELAY:ItemGarageProperty = new ItemGarageProperty(85,"DRONE_MINES_ACTIVATION_DELAY");
    public static const DRONE_MINES_PLACEMENT_RADIUS:ItemGarageProperty = new ItemGarageProperty(86,"DRONE_MINES_PLACEMENT_RADIUS");
    public static const DRONE_INVENTORY_COOLDOWN_BOOST:ItemGarageProperty = new ItemGarageProperty(87,"DRONE_INVENTORY_COOLDOWN_BOOST");
    public static const DRONE_POWER_BOOST:ItemGarageProperty = new ItemGarageProperty(88,"DRONE_POWER_BOOST");
    public static const DRONE_POWER_DURATION:ItemGarageProperty = new ItemGarageProperty(89,"DRONE_POWER_DURATION");
    public static const DRONE_CRITICAL_HEALTH:ItemGarageProperty = new ItemGarageProperty(90,"DRONE_CRITICAL_HEALTH");
    public static const DRONE_REPAIR_RADIUS:ItemGarageProperty = new ItemGarageProperty(91,"DRONE_REPAIR_RADIUS");
    public static const DRONE_INVENTORY_RADIUS:ItemGarageProperty = new ItemGarageProperty(92,"DRONE_INVENTORY_RADIUS");
    public static const DRONE_COOLDOWN_RADIUS:ItemGarageProperty = new ItemGarageProperty(93,"DRONE_COOLDOWN_RADIUS");
    public static const DRONE_CONSTANT_ARMOR_PERCENT:ItemGarageProperty = new ItemGarageProperty(94,"DRONE_CONSTANT_ARMOR_PERCENT");
    public static const DRONE_CONSTANT_POWER_PERCENT:ItemGarageProperty = new ItemGarageProperty(95,"DRONE_CONSTANT_POWER_PERCENT");
    public static const ULTIMATE_HEAL_HP:ItemGarageProperty = new ItemGarageProperty(96,"ULTIMATE_HEAL_HP");
    public static const ULTIMATE_CHARGE_PER_SEC:ItemGarageProperty = new ItemGarageProperty(97,"ULTIMATE_CHARGE_PER_SEC");
    public static const ULTIMATE_CHARGE_PER_SCORE_POINT:ItemGarageProperty = new ItemGarageProperty(98,"ULTIMATE_CHARGE_PER_SCORE_POINT");
    public static const ULTIMATE_SCORE_COOLDOWN_SEC:ItemGarageProperty = new ItemGarageProperty(99,"ULTIMATE_SCORE_COOLDOWN_SEC");
    public static const ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC:ItemGarageProperty = new ItemGarageProperty(100,"ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC");

    private var _value:int;
    private var _name:String;

    public function ItemGarageProperty(param1:int, param2:String) {
      super();
      this._value = param1;
      this._name = param2;
    }

    public static function get values() : Vector.<ItemGarageProperty> {
      var local1:Vector.<ItemGarageProperty> = new Vector.<ItemGarageProperty>();
      local1.push(HULL_ARMOR);
      local1.push(HULL_SPEED);
      local1.push(HULL_TURN_SPEED);
      local1.push(HULL_POWER);
      local1.push(HULL_MASS);
      local1.push(ALL_RESISTANCE);
      local1.push(FIREBIRD_RESISTANCE);
      local1.push(SMOKY_RESISTANCE);
      local1.push(TWINS_RESISTANCE);
      local1.push(RAILGUN_RESISTANCE);
      local1.push(ISIS_RESISTANCE);
      local1.push(MINE_RESISTANCE);
      local1.push(THUNDER_RESISTANCE);
      local1.push(FREEZE_RESISTANCE);
      local1.push(RICOCHET_RESISTANCE);
      local1.push(SHAFT_RESISTANCE);
      local1.push(SHOTGUN_RESISTANCE);
      local1.push(MACHINE_GUN_RESISTANCE);
      local1.push(ROCKET_LAUNCHER_RESISTANCE);
      local1.push(ARTILLERY_RESISTANCE);
      local1.push(GAUSS_RESISTANCE);
      local1.push(DAMAGE);
      local1.push(DAMAGE_PER_SECOND);
      local1.push(WEAPON_COOLDOWN_TIME);
      local1.push(AIMING_MODE_COOLDOWN_TIME);
      local1.push(CRITICAL_HIT_CHANCE);
      local1.push(CRITICAL_HIT_DAMAGE);
      local1.push(SHOT_RANGE);
      local1.push(TURRET_TURN_SPEED);
      local1.push(AIMING_ERROR);
      local1.push(SHOT_AREA);
      local1.push(CONE_ANGLE);
      local1.push(CHARGING_TIME);
      local1.push(FIRE_DAMAGE);
      local1.push(WEAPON_WEAKENING_COEFF);
      local1.push(ISIS_DAMAGE);
      local1.push(ISIS_HEALING_PER_SECOND);
      local1.push(AIMING_MODE_DAMAGE);
      local1.push(AIMING_WEAPON_DISCHARGE_RATE);
      local1.push(SHAFT_AIMED_SHOT_IMPACT);
      local1.push(SHAFT_TARGETING_SPEED);
      local1.push(SHAFT_ARCADE_DAMAGE);
      local1.push(GAUSS_AIMING_MODE_DAMAGE);
      local1.push(WEAPON_IMPACT_FORCE);
      local1.push(WEAPON_KICKBACK);
      local1.push(SHELL_SPEED);
      local1.push(WEAPON_CHARGE_RATE);
      local1.push(WEAPON_MIN_DAMAGE_PERCENT);
      local1.push(THUNDER_MIN_SPLASH_DAMAGE_PERCENT);
      local1.push(DEPENDENCY_FIRST_AID_SEC);
      local1.push(DEPENDENCY_DOUBLE_ARMOR_SEC);
      local1.push(DEPENDENCY_DOUBLE_DAMAGE_SEC);
      local1.push(DEPENDENCY_NITRO_SEC);
      local1.push(DEPENDENCY_MINE_SEC);
      local1.push(DEPENDENCY_DROPPABLE_GOLD_SEC);
      local1.push(COOLDOWN_FIRST_AID_SEC);
      local1.push(COOLDOWN_DOUBLE_ARMOR_SEC);
      local1.push(COOLDOWN_DOUBLE_DAMAGE_SEC);
      local1.push(COOLDOWN_NITRO_SEC);
      local1.push(COOLDOWN_MINE_SEC);
      local1.push(COOLDOWN_DROPPABLE_GOLD_SEC);
      local1.push(DURATION_FIRST_AID_SEC);
      local1.push(DURATION_DOUBLE_ARMOR_SEC);
      local1.push(DURATION_DOUBLE_DAMAGE_SEC);
      local1.push(DURATION_NITRO_SEC);
      local1.push(ATTACK_EFFECT);
      local1.push(FIRST_AID_EFFECT_INSTANT);
      local1.push(FIRST_AID_EFFECT);
      local1.push(PROTECTION_EFFECT);
      local1.push(SPEED_EFFECT);
      local1.push(SHOTGUN_IMPACT_FORCE);
      local1.push(DISCHARGE_SPEED);
      local1.push(FREEZE_PER_TICK);
      local1.push(VERTICAL_ANGLES);
      local1.push(DRONE_RELOAD);
      local1.push(DRONE_REPAIR_HEALTH);
      local1.push(DRONE_INVENTORY);
      local1.push(DRONE_INVENTORY_ADD);
      local1.push(DRONE_BONUS_ADD);
      local1.push(DRONE_FIRST_AID_BONUS_ADD);
      local1.push(DRONE_OVERDRIVE_BOOST);
      local1.push(DRONE_DEFEND);
      local1.push(DRONE_ARMOR_BOOST);
      local1.push(DRONE_MINE);
      local1.push(DRONE_ADDITIONAL_MINES);
      local1.push(DRONE_MINES_ACTIVATION_DELAY);
      local1.push(DRONE_MINES_PLACEMENT_RADIUS);
      local1.push(DRONE_INVENTORY_COOLDOWN_BOOST);
      local1.push(DRONE_POWER_BOOST);
      local1.push(DRONE_POWER_DURATION);
      local1.push(DRONE_CRITICAL_HEALTH);
      local1.push(DRONE_REPAIR_RADIUS);
      local1.push(DRONE_INVENTORY_RADIUS);
      local1.push(DRONE_COOLDOWN_RADIUS);
      local1.push(DRONE_CONSTANT_ARMOR_PERCENT);
      local1.push(DRONE_CONSTANT_POWER_PERCENT);
      local1.push(ULTIMATE_HEAL_HP);
      local1.push(ULTIMATE_CHARGE_PER_SEC);
      local1.push(ULTIMATE_CHARGE_PER_SCORE_POINT);
      local1.push(ULTIMATE_SCORE_COOLDOWN_SEC);
      local1.push(ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC);
      return local1;
    }

    public function toString() : String {
      return "ItemGarageProperty [" + this._name + "]";
    }

    public function get value() : int {
      return this._value;
    }

    public function get name() : String {
      return this._name;
    }
  }
}
